### ISSUE TITLE
Getting params error from inverse-futures-client getPosition method

### ISSUE THREAD

**Issue by jeffminsungkim** [tiagosiebler/bybit-api#112]
Hi. Thank you for your hard work on this project!
There's one problem when I use `getPosition` method from inverse-futures-client.ts file.
I'm getting `params error` when I pass the symbol property like below.
Could you please tell me what should be fixed here?

```javascript
const { InverseFuturesClient } = require('bybit-api');
const client = new InverseFuturesClient(API_KEY, PRIVATE_KEY, true);

client.getPosition({ symbol: 'BTCUSD' }).then(res => {
  // getting an error ret_msg: "params error!"
});
```

Thank you.

**Comment by jeffminsungkim** [comment]
@tiagosiebler 
I've found out that the endpoint has been changed.
` cancelAllActiveOrders` method points to an incorrect endpoint. It should be `/v2/private/order/cancelAll` not `futures/private/order/cancelAll`

Do you want me to create a PR?

**Comment by tiagosiebler** [comment]
Hey @jeffminsungkim - was there an issue here still? Looking at cancelAllActiveOrders it seems to be using the endpoint you've mentioned:
https://github.com/tiagosiebler/bybit-api/blob/master/src/inverse-futures-client.ts#L134-L138
