### ISSUE TITLE
Using sync_interval_ms causes, rather than prevents, time drift

### ISSUE THREAD

**Issue by tallytarik** [tiagosiebler/bybit-api#119]
First off, thanks for this great API implementation :)

I have a script which is long-running which occasionally makes API requests to ByBit.

I noticed that after a while, all API requests start failing with the standard "check your revcwindow/timestamp" error. It reports that my time and the server time is a few seconds off. 

I found the `sync_interval_ms` param, so I tried lowering this value so it would sync every minute. I saw some interesting behaviour: the API requests started failing much earlier... roughly a minute after my script started.

So it seems like the 'time sync' actually *caused* the API errors to start happening. To test this further, I've set `sync_interval_ms` to a very high value, like ~100 hours, and now have had my script running for a couple of days without issue.

Sorry if this is a bit light on detail - happy to send through anything else that'll help with debugging.

Cheers

**Comment by tiagosiebler** [comment]
Nothing to apologise for! This is extremely helpful. I've had mixed results, with no issues in lower frequency trading but I seem to be getting recv errors overnight (always in the same time window) on higher frequency trading (albeit with my binance connector, which uses the same mechanism). 

As you can imagine I've started to wonder if the sync mechanism doesn't work as well as I initially hoped, at least not in the current state.

I'm curious whether you'll see any recvwindow errors after the sync_interval_ms window has passed a few times. Seems it should fire every 4 days now, so two weeks might give a better estimate whether to raise the default time sync interval. Could you keep me posted?

Thanks!

**Comment by tiagosiebler** [comment]
Hey @tallytarik - wanted to check in on this two months later, how is this behaving for you now?

**Comment by tallytarik** [comment]
Whoops, sorry I didn't reply earlier!

I've had my `sync_interval_ms` set to 7 days (`604_800_000`), which is about as long as my script would ever be running without a restart. It's all been working great. I suspect if my script ran for longer than 7 days (beyond the sync_interval_ms), I'd see those same errors again.

I get the occasional recv_window API error, probably <10 per day, while updating wallet/position data. They're infrequent enough that I suspect they're either an API or network hiccup.

**Comment by tiagosiebler** [comment]
No worries! The intention for the sync was to reduce the frequency of the recv window errors even further. I do think due to a small sample size (one bad request), during a network or api hiccup it can severely offset the timestamp ms far too much, causing more problems than it solves... I think it might be too aggressive. Will need to revisit it in future. 

Also hesitant whether to turn it off by default... feels like a chicken <-> egg situation. Either it's on by default, solves a lot of recv window errors until it on a rare chance causes them, or it's off by default and doesn't solve any recv window errors.

Either way it'll always lead to questions on how to deal with recv window errors without regular machine clock sync calls on the environment itself...

**Comment by tallytarik** [comment]
That makes sense - I suspected that's what the sync was trying to do.

Not sure why it breaks on my end when it's enabled, since it sounds like it works for you and others. I'm happy just running my scripts with a huge `sync_interval_ms` (basically just turning it off), so maybe no change is needed here. Perhaps a note in the readme/comments about how it's works?

**Comment by tiagosiebler** [comment]
As of v2.3.0 (#159), time sync is now disabled by default for this connector. It can still be enabled optionally through the `enable_time_sync` property in the rest client constructor options.
