### ISSUE TITLE
Question: Why is command line still open after closing websocket connection?

### ISSUE THREAD

**Issue by doppelgunner** [tiagosiebler/bybit-api#127]
Question: Why is command line still open after closing websocket connection?

    const wsConfig = {
        key: userExchange.apiKey,
        secret: userExchange.privateKey,
    };

    const ws = new WebsocketClient(wsConfig)
    ws.subscribe('kline.BTCUSD.1s');

    ws.on('open',({wsKey, event}) => {
        wsKey = wsKey;
        console.log('connection open for websocket with ID: ' + wsKey);
    })

    ws.on('update', data => {
        console.log('update', data);
    });

    ws.on('close', () => {
        console.log('connection closed');
      });

    setTimeout(() => {
        console.log('closing', 'inverse')
        ws.close('inverse');
    }, 3000)

Command line is still open? - https://prnt.sc/23uyvmd

**Comment by tiagosiebler** [comment]
I think I see why this is happening. The ws client has a dependency on the REST client:
https://github.com/tiagosiebler/bybit-api/blob/master/src/websocket-client.ts#L217-L225

This is primarily for the time offset (used during authentication as part of the timestamp sent to the server). The REST client has a timer running (for the timestamp offset) that queries the time endpoint at intervals to estimate latency. That timer must be keeping the process running.

If you do want to close the process, why not call `process.exit()`?
https://nodejs.org/api/process.html#processexitcode

**Comment by doppelgunner** [comment]
you are a genius!!!

**Comment by zhaoxiaohai** [comment]
> I think I see why this is happening. The ws client has a dependency on the REST client: https://github.com/tiagosiebler/bybit-api/blob/master/src/websocket-client.ts#L217-L225
> 
> This is primarily for the time offset (used during authentication as part of the timestamp sent to the server). The REST client has a timer running (for the timestamp offset) that queries the time endpoint at intervals to estimate latency. That timer must be keeping the process running.
> 
> If you do want to close the process, why not call `process.exit()`? https://nodejs.org/api/process.html#processexitcode

Is there any other way to just shut it down? I also need the process to continue running, just temporarily closing the connection
