### ISSUE TITLE
Bulky LIMIT ORDERS

### ISSUE THREAD

**Issue by DENNIS-CODES** [tiagosiebler/bybit-api#135]
does this api offers placing bulky limit order, I want to place 5 limit orders at once and 1 buy order through a POST endpoint,  but am getting params error on some of the orders, and some orders are placed, my endpoint only receive one set of data only the price changes each time, when testing my endpoint locally all orders are submitted without issues but on the server i get params error

**Comment by tiagosiebler** [comment]
I don't recall seeing an endpoint for placing bulk orders, but if you want to double-check you can:
- check the appropriate section of their api docs: https://bybit-exchange.github.io/docs/linear/#t-introduction
- ask in their official api telegram support group: https://t.me/BybitAPI

What I've done in the past is create an array of desired orders, then use map to trigger an api call for each order object (collecting all promises into a new array), then use `Promise.allSettled(arrayOfPromises)` to wait for all orders to resolve or reject.

**Comment by DENNIS-CODES** [comment]
What is the rate limit and how many orders can be submitted per millisecond

**Comment by DENNIS-CODES** [comment]
I found out Bybit doesn't accept orders with prices that have more than one decimal point such as price  `40356.5999544` this will raise params error which was the case for me,  `prices` should be `40356.6` or `40356`, then again thank you for your advice I mapped the orders and passed them in a for a loop this made it possible to implement sleep function after placing an order
