### ISSUE TITLE
Unhandled promise at websocket client

### ISSUE THREAD

**Issue by GorWebfoundation** [tiagosiebler/bybit-api#138]
webcocket-client.js: 7
function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }

missing .catch, which is being a reason of throwing error

**Comment by tiagosiebler** [comment]
Can you wrap your logic inside your event handler in a try/catch block? Most error reports I've seen from the websocket client are actually exceptions thrown from implementation code, not from the library. If you throw and don't catch your own exception inside the event handler, it'll get caught by the websocket client.

If the issue persists, please provide a simple scenario to reproduce the issue.
