### ISSUE TITLE
we need to add function for linear-client.ts

### ISSUE THREAD

**Issue by kliperd** [tiagosiebler/bybit-api#144]
![image](https://user-images.githubusercontent.com/10215356/161919573-23bbcb98-d7af-44e7-8e7b-62feb4ec9c74.png)

It exsits ' private/linear/tpsl/switch-mode' function.

But there no function '/private/linear/position/switch-mode'  for **Position Mode Switch**
 

==>

   setSwitchMode(params) {       
        return this.requestWrapper.post('private/linear/tpsl/switch-mode', params);
    }

setPositionSwitchMode(params) {       
        return this.requestWrapper.post('private/linear/**position/switch-mode**', params);
    }

**Comment by tiagosiebler** [comment]
Either I missed it or it was added recently. I've added the missing endpoint in #146, it should be available on npm under version v2.1.10 shortly. Thanks!
