### ISSUE TITLE
Code Error -2015 on valid API KEY 

### ISSUE THREAD

**Issue by ATCBGroup** [tiagosiebler/bybit-api#149]
Hi ! 

I started to play and when I try to get my Spot Balance by using my API Key and Secret (and I know that they're valid as I used in parallel the same key for python and also works on another library JS), I always get the following error :

**Error :**

getBalances result:  {
  ret_code: -2015,
  ret_msg: 'Invalid API-key, IP, or permissions for action.',
  ext_code: null,
  ext_info: null,
  result: null
}

**My Code :** 
`const { SpotClient } = require("bybit-api");

const API_KEY = "myKey"; // Of course I change with the correct one
const PRIVATE_KEY = "myPrivateKey"; // Of course I change with the correct one
const useLivenet = false;

const client = new SpotClient(
  API_KEY,
  PRIVATE_KEY,
  useLivenet
);

client
  .getBalances()
  .then((result) => {
    console.log("getBalances result: ", result);
  })
  .catch((err) => {
    console.error("getBalances error: ", err);
  });
`

The error is the same with Inverse, InverseFutures, etc. The test with another lib ('ccxt') is working well on the same machine
Any ideas ? 

Thanks a lot for your work !

**Comment by ATCBGroup** [comment]
Issue has been solved on my side. It runs now without changing. My only guess is:
- Problem of sync (weird because I used Python with PyBit in the same machine with same API)

**Comment by tiagosiebler** [comment]
Strange to hear this...especially since it worked with other connectors, but glad to hear it's working now.
