### ISSUE TITLE
Struggling with linear WS: handler not found

### ISSUE THREAD

**Issue by MrAlvaroPS** [tiagosiebler/bybit-api#154]
Hello!

I'm trying to connect to WS for Kline data but I'm getting this error all the time.

I just followed the "examples" folder but it doesn't work for me.

This is an screenshot of the error log

![image](https://user-images.githubusercontent.com/31500250/176154401-68232583-96a7-4cdd-b26f-c93bdd0d68ef.png)

Anyone can help me?

**Comment by tiagosiebler** [comment]
For the linear (USDT Perps) topics, the syntax seems to be `candle.1.BTCUSDT` for 1 minute btcusdt candles. Can you try that?

Docs: https://bybit-exchange.github.io/docs/linear/#t-websocketkline

**Comment by MrAlvaroPS** [comment]
Just saw that too. 

It seems like they have something wrong in their API:
![image](https://user-images.githubusercontent.com/31500250/176155851-8d340bcb-3566-4bab-80c9-a17f7cca50c4.png)

But I just success with "candle". 

Thank you very much!

**Comment by tiagosiebler** [comment]
Where do you see this?

**Comment by MrAlvaroPS** [comment]
In the section "How to Subscribe to Topics". 

On your right there is a tittle that says "subscription response".

**Comment by tiagosiebler** [comment]
Thanks - passed it on to my bybit contacts, they'll get it fixed. For a list of topics it's better to refer to the dedicated section further down in the docs

**Comment by MrAlvaroPS** [comment]
Yeah, I just realized that. 

I know pretty well the Binance API but this is my first approach to ByBit.

Thank you again and keep up with this great work 💯

**Comment by tiagosiebler** [comment]
> Yeah, I just realized that.
> 
> I know pretty well the Binance API but this is my first approach to ByBit.
> 
> Thank you again and keep up with this great work 💯

There's unfortunately quite a few differences between the different API categories in bybit. Afaik they're planning on releasing a more consistent API sometime in the coming year
