### ISSUE TITLE
Anyone help with a api call?

### ISSUE THREAD

**Issue by rafaelfaria** [tiagosiebler/bybit-api#162]
I am very confused with the APIs. 

Anyone could help me with the following requests:

1. Open a leverage market order of MATIC (USDT Perpetual) of 10 dollars, leverage 10x, iso margin, with stop loss set (-10% of the entry)
2. Adjust the stop loss of an existing order
3. Close an order

If you have done any of the above and can help, it would be much appreciated :)

**Comment by emorling** [comment]
For USDT Perpetual you must use the LinearClient.

```
const { LinearClient } = require('bybit-api');
const client = new LinearClient(
      API_KEY,
      API_SECRET
);
```

First you must set leverage and isolated. There is a quirk of ByBit: you cant set a new leverage if the its already isolated. To circumvent switch from Isolated to Cross and then back again:

```
await client.setMarginSwitch({
      symbol: 'MATICUSDT',
      is_isolated: false,
      buy_leverage: 10,
      sell_leverage: 10,
    });
    await client.setMarginSwitch({
      symbol: 'MATICUSDT',
      is_isolated: true,
      buy_leverage: 10,
      sell_leverage: 10,
    });
```
Use this to create the order:

`client.placeActiveOrder(params)
`

And this to edit the order (e.g. to adjust stop loss)
`client.replaceActiveOrder(params)
`

**Comment by tiagosiebler** [comment]
For anyone finding this, RestClientV5 should now be used instead of the LinearClient. Closing this as resolved.
