### ISSUE TITLE
Identify a Conditional Order for an Open Position

### ISSUE THREAD

**Issue by emorling** [tiagosiebler/bybit-api#172]
This question is not directly related to the library. 

Which fields can I use to differentiate between "regular" conditional orders and the ones created by setting SL/TP on an open position? 

These are characteristics of conditional orders for open positions:

order.side === 'Sell' 
order_type === 'Market'
order.price === 0
order.time_in_force === 'ImmediateOrCancel' 
order.reduce_only === true
order.close_on_trigger  === true

Do I need to check all of these fields, or can I narrow it down? thanks

**Comment by tiagosiebler** [comment]
Unfortunately don't know to the answer to this one. If nobody else does either, the support team in the API telegram is usually pretty good: https://t.me/BybitAPI

**Comment by emorling** [comment]
Ok!
