### ISSUE TITLE
Handle more than 10 subscriptions in websocket

### ISSUE THREAD

**Issue by stopak** [tiagosiebler/bybit-api#174]
Hi, I've tried to have more than 10 subscriptions at the same time. The BYBIT api allows only 10 topics to be sent in single call.

**Comment by tiagosiebler** [comment]
Is this a limitation per subscription event? Or a limitation per websocket connection? I don't see anything about this in the API docs.

**Comment by stopak** [comment]
It looks like API limitation per subscription event. I've succesfully created 100+ subscriptions using `requestSubscribeTopics`. However I need to track and resubmit subscriptions on reconnection event.

Error message from BYBIT:

`({
      op: 'subscribe',
      success: false,
      req_id: 'orderbook.40.BTCUSDT,orderbook.40.BTCUSDC,orderbook.40.USDCUSDT,orderbook.40.BTCDAI,orderbook.40.DAIUSDT,orderbook.40.ETHUSDT,orderbook.40.ETHUSDC,orderbook.40.ETHDAI,orderbook.40.XRPUSDT,orderbook.40.XRPUSDC,orderbook.40.EOSUSDT,orderbook.40.EOSUSDC,orderbook.40.DOTUSDT,orderbook.40.DOTUSDC,orderbook.40.XLMUSDT,orderbook.40.XLMUSDC,orderbook.40.LTCUSDT,orderbook.40.LTCUSDC,orderbook.40.DOGEUSDT,orderbook.40.DOGEUSDC,orderbook.40.BITUSDT,orderbook.40.BITUSDC,orderbook.40.BITDAI,orderbook.40.CHZUSDT,orderbook.40.CHZUSDC,orderbook.40.MANAUSDT,orderbook.40.MANAUSDC,orderbook.40.LINKUSDT,orderbook.40.LINKUSDC,orderbook.40.ICPUSDT,orderbook.40.ICPUSDC,orderbook.40.ADAUSDT,orderbook.40.ADAUSDC,orderbook.40.SOLUSDC,orderbook.40.SOLUSDT,orderbook.40.MATICUSDC,orderbook.40.MATICUSDT,orderbook.40.SANDUSDC,orderbook.40.SANDUSDT,orderbook.40.LUNCUSDC,orderbook.40.LUNCUSDT,orderbook.40.SLGUSDC,orderbook.40.SLGUSDT,orderbook.40.AVAXUSDC,orderbook.40.AVAXUSDT,orderbook.40.OPUSDC,orderbook.40.OPUSDT,orderbook.40.OKSEUSDC,orderbook.40.OKSEUSDT,orderbook.40.APEXUSDC,orderbook.40.APEXUSDT,orderbook.40.TRXUSDC,orderbook.40.TRXUSDT,orderbook.40.GMTUSDC,orderbook.40.GMTUSDT,orderbook.40.SHIBUSDC,orderbook.40.SHIBUSDT,orderbook.40.LDOUSDC,orderbook.40.LDOUSDT,orderbook.40.APEUSDC,orderbook.40.APEUSDT,orderbook.40.FILUSDC,orderbook.40.FILUSDT',
      ret_msg: 'args size >10',
      conn_id: '1567369f',
      wsKey: 'spotV3Public'
    })`

**Comment by tiagosiebler** [comment]
@stopak You should use the `wsClient.subscribe(topics)` method. This way, the library will keep track of subscribed events and will resubscribe if the connection drops/reconnects.

The requestSubscribeTopics is actually an internal/private method used in the final part of the subscribe workflow (after updating records on which topics to stay subscribed to), it's marked as "private" for that reason:
https://github.com/tiagosiebler/bybit-api/blob/master/src/websocket-client.ts#L508

The subscribe method updates internal state, opens a connection if it isn't open yet, and ensures your requested topics are subscribed to: 
https://github.com/tiagosiebler/bybit-api/blob/master/src/websocket-client.ts#L779

It looks like only spot v3 has this limitation per event (not per connection). I must have missed it when working through this, or it was only recently documented. I've pushed an improvement in #176 to automatically handle batching for you, just make sure you're using subscribe() and unsubscribe(), not the request* methods.

It should be released as 3.0.2 shortly as soon as the github action finishes. Gave it a quick try on my end with the `examples/ws-public.ts` sample, can you give it a go once it's released?

**Comment by stopak** [comment]
Sure, I'm waiting for version 3.0.2

**Comment by tiagosiebler** [comment]
> Sure, I'm waiting for version 3.0.2

It's available now, should be fixed there with automatic batching. Just call `ws.subscribe(arrayOfTopics)` with as many topics as you want and it should automatically do smaller chunks. You can also try killing your wifi to test the re-subscribing works fine.
