### ISSUE TITLE
Request header change

### ISSUE THREAD

**Issue by GorWebfoundation** [tiagosiebler/bybit-api#191]
Hi, Thanks for awesome package.
How can I put referer header when calling order APIs?

**Comment by tiagosiebler** [comment]
Hi @GorWebfoundation - do you have telegram? If so, can you contact me to discuss this? This is my telegram: https://t.me/AlgoTraderL

For anyone else with a similar query, please reach out in telegram.

**Comment by tiagosiebler** [comment]
Closing this, since we're discussing in telegram. Thanks
