### ISSUE TITLE
Reconnection failed: 'Websocket error due to unexpected response error: "read ECONNRESET"'

### ISSUE THREAD

**Issue by oDYRASH** [tiagosiebler/bybit-api#192]
[
  'Websocket error due to unexpected response error: "read ECONNRESET"',
  {
    category: 'bybit-ws',
    wsKey: 'spotV3Private',
    error: ErrorEvent {
      target: [WebSocket],
      type: 'error',
      message: 'read ECONNRESET',
      error: [Error]
    }
  }
]
node:events:517
    throw err; // Unhandled 'error' event
    ^

Error [ERR_UNHANDLED_ERROR]: Unhandled error. (ErrorEvent {
  target: WebSocket {
    _events: [Object: null prototype] {
      open: [Function],
      message: [Function],
      error: [Function],
      close: [Function]
    },
    _eventsCount: 4,
    _maxListeners: undefined,
    readyState: 2,
    protocol: '',
    _binaryType: 'nodebuffer',
    _finalize: [Function: bound finalize],
    _closeFrameReceived: false,
    _closeFrameSent: false,
    _closeMessage: '',
    _closeTimer: null,
    _finalized: true,
    _closeCode: 1006,
    _extensions: {},
    _isServer: false,
    _receiver: Receiver {
      _binaryType: 'nodebuffer',
      _extensions: null,
      _maxPayload: 0,
      _bufferedBytes: 0,
      _buffers: null,
      _compressed: false,
      _payloadLength: 111,
      _fragmented: 0,
      _masked: false,
      _fin: true,
      _mask: null,
      _opcode: 1,
      _totalPayloadLength: 0,
      _messageLength: 0,
      _fragments: null,
      _cleanupCallback: null,
      _isCleaningUp: false,
      _hadError: false,
      _loop: false,
      add: [Function: bound add],
      onmessage: null,
      onclose: null,
      onerror: null,
      onping: null,
      onpong: null,
      _state: 0
    },
    _sender: Sender {
      _extensions: {},
      _socket: [TLSSocket],
      _firstFragment: true,
      _compress: false,
      _bufferedBytes: 0,
      _deflating: false,
      _queue: []
    },
    _socket: TLSSocket {
      _tlsOptions: [Object],
      _secureEstablished: true,
      _securePending: false,
      _newSessionPending: false,
      _controlReleased: true,
      secureConnecting: false,
      _SNICallback: null,
      servername: 'stream.bybit.com',
      alpnProtocol: false,
      authorized: true,
      authorizationError: null,
      encrypted: true,
      _events: [Object: null prototype],
      _eventsCount: 6,
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: 'stream.bybit.com',
      _readableState: [ReadableState],
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: undefined,
      _server: null,
      ssl: null,
      _requestCert: true,
      _rejectUnauthorized: true,
      parser: null,
      _httpMessage: null,
      timeout: 0,
      [Symbol(res)]: [TLSWrap],
      [Symbol(verified)]: true,
      [Symbol(pendingSession)]: null,
      [Symbol(async_id_symbol)]: 46825,
      [Symbol(kHandle)]: null,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: null,
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kBytesRead)]: 67127,
      [Symbol(kBytesWritten)]: 10188,
      [Symbol(connect-options)]: [Object],
      [Symbol(RequestTimeout)]: undefined
    },
    _error: null,
    url: 'wss://stream.bybit.com/spot/private/v3?api_key=aaaaaa&expires=1667063591282&signature=aaaaa',
    _req: null,
    [Symbol(kCapture)]: false
  },
  type: 'error',
  message: 'read ECONNRESET',
  error: Error: read ECONNRESET
      at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
    errno: -4077,
    code: 'ECONNRESET',
    syscall: 'read'
  }
})
    at new NodeError (node:internal/errors:371:5)
    at WebsocketClient.emit (node:events:515:17)
    at WebsocketClient.parseWsError (C:\Users\Tony\node_modules\bybit-api\lib\websocket-client.js:268:14)
    at WebsocketClient.onWsError (C:\Users\Tony\node_modules\bybit-api\lib\websocket-client.js:524:14)
    at WebSocket.ws.onerror (C:\Users\Tony\node_modules\bybit-api\lib\websocket-client.js:453:38)
    at WebSocket.onError (C:\Users\Tony\node_modules\ws\lib\event-target.js:128:16)
    at WebSocket.emit (node:events:526:28)
    at C:\Users\Tony\node_modules\ws\lib\websocket.js:211:14
    at Receiver.cleanup (C:\Users\Tony\node_modules\ws\lib\receiver.js:557:13)
    at WebSocket.finalize (C:\Users\Tony\node_modules\ws\lib\websocket.js:206:20) {
  code: 'ERR_UNHANDLED_ERROR',
  context: ErrorEvent {
    target: WebSocket {
      _events: [Object: null prototype] {
        open: [Function: onOpen] { _listener: [Function (anonymous)] },
        message: [Function: onMessage] { _listener: [Function (anonymous)] },
        error: [Function: onError] { _listener: [Function (anonymous)] },
        close: [Function: onClose] { _listener: [Function (anonymous)] }
      },
      _eventsCount: 4,
      _maxListeners: undefined,
      readyState: 2,
      protocol: '',
      _binaryType: 'nodebuffer',
      _finalize: [Function: bound finalize],
      _closeFrameReceived: false,
      _closeFrameSent: false,
      _closeMessage: '',
      _closeTimer: null,
      _finalized: true,
      _closeCode: 1006,
      _extensions: {},
      _isServer: false,
      _receiver: Receiver {
        _binaryType: 'nodebuffer',
        _extensions: null,
        _maxPayload: 0,
        _bufferedBytes: 0,
        _buffers: null,
        _compressed: false,
        _payloadLength: 111,
        _fragmented: 0,
        _masked: false,
        _fin: true,
        _mask: null,
        _opcode: 1,
        _totalPayloadLength: 0,
        _messageLength: 0,
        _fragments: null,
        _cleanupCallback: null,
        _isCleaningUp: false,
        _hadError: false,
        _loop: false,
        add: [Function: bound add],
        onmessage: null,
        onclose: null,
        onerror: null,
        onping: null,
        onpong: null,
        _state: 0
      },
      _sender: Sender {
        _extensions: {},
        _socket: <ref *1> TLSSocket {
          _tlsOptions: {
            allowHalfOpen: undefined,
            pipe: false,
            secureContext: [SecureContext],
            isServer: false,
            requestCert: true,
            rejectUnauthorized: true,
            session: [Buffer [Uint8Array]],
            ALPNProtocols: undefined,
            requestOCSP: undefined,
            enableTrace: undefined,
            pskCallback: undefined,
            highWaterMark: undefined,
            onread: undefined,
            signal: undefined
          },
          _secureEstablished: true,
          _securePending: false,
          _newSessionPending: false,
          _controlReleased: true,
          secureConnecting: false,
          _SNICallback: null,
          servername: 'stream.bybit.com',
          alpnProtocol: false,
          authorized: true,
          authorizationError: null,
          encrypted: true,
          _events: [Object: null prototype] {
            close: [Array],
            end: [Function: onReadableStreamEnd],
            newListener: [Function: keylogNewListener],
            secure: [Function: onConnectSecure],
            session: [Function (anonymous)],
            error: [Function (anonymous)]
          },
          _eventsCount: 6,
          connecting: false,
          _hadError: false,
          _parent: null,
          _host: 'stream.bybit.com',
          _readableState: ReadableState {
            objectMode: false,
            highWaterMark: 16384,
            buffer: [BufferList],
            length: 0,
            pipes: [],
            flowing: true,
            ended: false,
            endEmitted: false,
            reading: true,
            constructed: true,
            sync: false,
            needReadable: true,
            emittedReadable: false,
            readableListening: false,
            resumeScheduled: false,
            errorEmitted: true,
            emitClose: false,
            autoDestroy: true,
            destroyed: true,
            errored: [Error],
            closed: true,
            closeEmitted: false,
            defaultEncoding: 'utf8',
            awaitDrainWriters: null,
            multiAwaitDrain: false,
            readingMore: false,
            dataEmitted: true,
            decoder: null,
            encoding: null,
            [Symbol(kPaused)]: false
          },
          _maxListeners: undefined,
          _writableState: WritableState {
            objectMode: false,
            highWaterMark: 16384,
            finalCalled: false,
            needDrain: false,
            ending: false,
            ended: false,
            finished: false,
            destroyed: true,
            decodeStrings: false,
            defaultEncoding: 'utf8',
            length: 0,
            writing: false,
            corked: 0,
            sync: false,
            bufferProcessing: false,
            onwrite: [Function: bound onwrite],
            writecb: null,
            writelen: 0,
            afterWriteTickInfo: null,
            buffered: [],
            bufferedIndex: 0,
            allBuffers: true,
            allNoop: true,
            pendingcb: 0,
            constructed: true,
            prefinished: false,
            errorEmitted: true,
            emitClose: false,
            autoDestroy: true,
            errored: [Error],
            closed: true,
            closeEmitted: false,
            [Symbol(kOnFinished)]: []
          },
          allowHalfOpen: false,
          _sockname: null,
          _pendingData: null,
          _pendingEncoding: '',
          server: undefined,
          _server: null,
          ssl: null,
          _requestCert: true,
          _rejectUnauthorized: true,
          parser: null,
          _httpMessage: null,
          timeout: 0,
          [Symbol(res)]: TLSWrap {
            _parent: [TCP],
            _parentWrap: undefined,
            _secureContext: [SecureContext],
            reading: true,
            onkeylog: [Function: onkeylog],
            onhandshakestart: {},
            onhandshakedone: [Function (anonymous)],
            onocspresponse: [Function: onocspresponse],
            onnewsession: [Function: onnewsessionclient],
            onerror: [Function: onerror],
            [Symbol(owner_symbol)]: [Circular *1]
          },
          [Symbol(verified)]: true,
          [Symbol(pendingSession)]: null,
          [Symbol(async_id_symbol)]: 46825,
          [Symbol(kHandle)]: null,
          [Symbol(kSetNoDelay)]: true,
          [Symbol(lastWriteQueueSize)]: 0,
          [Symbol(timeout)]: null,
          [Symbol(kBuffer)]: null,
          [Symbol(kBufferCb)]: null,
          [Symbol(kBufferGen)]: null,
          [Symbol(kCapture)]: false,
          [Symbol(kBytesRead)]: 67127,
          [Symbol(kBytesWritten)]: 10188,
          [Symbol(connect-options)]: {
            rejectUnauthorized: true,
            ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
            checkServerIdentity: [Function: checkServerIdentity],
            minDHSize: 1024,
            session: [Buffer [Uint8Array]],
            port: 443,
            host: 'stream.bybit.com',
            path: null,
            headers: [Object],
            _defaultAgent: [Agent],
            servername: 'stream.bybit.com',
            _agentKey: 'stream.bybit.com:443:::::::::::::::::::::',
            encoding: null,
            singleUse: true
          },
          [Symbol(RequestTimeout)]: undefined
        },
        _firstFragment: true,
        _compress: false,
        _bufferedBytes: 0,
        _deflating: false,
        _queue: []
      },
      _socket: <ref *1> TLSSocket {
        _tlsOptions: {
          allowHalfOpen: undefined,
          pipe: false,
          secureContext: SecureContext { context: SecureContext {} },
          isServer: false,
          requestCert: true,
          rejectUnauthorized: true,
          session: Buffer(1751) [Uint8Array] [
             48, 130,   6, 211,   2,   1,   1,   2,   2,   3,   4,   4,
              2,  19,   1,   4,  32, 176,  72,  80, 167, 154, 110, 115,
             79, 231, 122, 236, 138,  59,  74,  79, 216, 171,  47,  69,
            126,  94, 176, 237, 191, 139,  23,  10,   1, 191, 144, 109,
            245,   4,  32, 171, 202,  47, 226, 246,   6, 189,  47, 114,
            171, 222, 168,  62, 131, 251,  62,  28, 144, 189,  51, 224,
             45, 114, 243, 105,  81, 240, 117,  15,  71,  58,  54, 161,
              6,   2,   4,  99,  93,  95,  31, 162,   4,   2,   2,  28,
             32, 163, 130,   5,
            ... 1651 more items
          ],
          ALPNProtocols: undefined,
          requestOCSP: undefined,
          enableTrace: undefined,
          pskCallback: undefined,
          highWaterMark: undefined,
          onread: undefined,
          signal: undefined
        },
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        secureConnecting: false,
        _SNICallback: null,
        servername: 'stream.bybit.com',
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object: null prototype] {
          close: [ [Function: onSocketCloseDestroySSL], [Function] ],
          end: [Function: onReadableStreamEnd],
          newListener: [Function: keylogNewListener],
          secure: [Function: onConnectSecure],
          session: [Function (anonymous)],
          error: [Function (anonymous)]
        },
        _eventsCount: 6,
        connecting: false,
        _hadError: false,
        _parent: null,
        _host: 'stream.bybit.com',
        _readableState: ReadableState {
          objectMode: false,
          highWaterMark: 16384,
          buffer: BufferList { head: null, tail: null, length: 0 },
          length: 0,
          pipes: [],
          flowing: true,
          ended: false,
          endEmitted: false,
          reading: true,
          constructed: true,
          sync: false,
          needReadable: true,
          emittedReadable: false,
          readableListening: false,
          resumeScheduled: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          destroyed: true,
          errored: Error: read ECONNRESET
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
            errno: -4077,
            code: 'ECONNRESET',
            syscall: 'read'
          },
          closed: true,
          closeEmitted: false,
          defaultEncoding: 'utf8',
          awaitDrainWriters: null,
          multiAwaitDrain: false,
          readingMore: false,
          dataEmitted: true,
          decoder: null,
          encoding: null,
          [Symbol(kPaused)]: false
        },
        _maxListeners: undefined,
        _writableState: WritableState {
          objectMode: false,
          highWaterMark: 16384,
          finalCalled: false,
          needDrain: false,
          ending: false,
          ended: false,
          finished: false,
          destroyed: true,
          decodeStrings: false,
          defaultEncoding: 'utf8',
          length: 0,
          writing: false,
          corked: 0,
          sync: false,
          bufferProcessing: false,
          onwrite: [Function: bound onwrite],
          writecb: null,
          writelen: 0,
          afterWriteTickInfo: null,
          buffered: [],
          bufferedIndex: 0,
          allBuffers: true,
          allNoop: true,
          pendingcb: 0,
          constructed: true,
          prefinished: false,
          errorEmitted: true,
          emitClose: false,
          autoDestroy: true,
          errored: Error: read ECONNRESET
              at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
            errno: -4077,
            code: 'ECONNRESET',
            syscall: 'read'
          },
          closed: true,
          closeEmitted: false,
          [Symbol(kOnFinished)]: []
        },
        allowHalfOpen: false,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: null,
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: null,
        timeout: 0,
        [Symbol(res)]: TLSWrap {
          _parent: TCP {
            reading: [Getter/Setter],
            onconnection: null,
            [Symbol(owner_symbol)]: [Circular *1],
            [Symbol(handle_onclose)]: [Function: done]
          },
          _parentWrap: undefined,
          _secureContext: SecureContext { context: SecureContext {} },
          reading: true,
          onkeylog: [Function: onkeylog],
          onhandshakestart: {},
          onhandshakedone: [Function (anonymous)],
          onocspresponse: [Function: onocspresponse],
          onnewsession: [Function: onnewsessionclient],
          onerror: [Function: onerror],
          [Symbol(owner_symbol)]: [Circular *1]
        },
        [Symbol(verified)]: true,
        [Symbol(pendingSession)]: null,
        [Symbol(async_id_symbol)]: 46825,
        [Symbol(kHandle)]: null,
        [Symbol(kSetNoDelay)]: true,
        [Symbol(lastWriteQueueSize)]: 0,
        [Symbol(timeout)]: null,
        [Symbol(kBuffer)]: null,
        [Symbol(kBufferCb)]: null,
        [Symbol(kBufferGen)]: null,
        [Symbol(kCapture)]: false,
        [Symbol(kBytesRead)]: 67127,
        [Symbol(kBytesWritten)]: 10188,
        [Symbol(connect-options)]: {
          rejectUnauthorized: true,
          ciphers: 'TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_128_GCM_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA384:DHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA256:DHE-RSA-AES256-SHA256:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!SRP:!CAMELLIA',
          checkServerIdentity: [Function: checkServerIdentity],
          minDHSize: 1024,
          session: Buffer(1751) [Uint8Array] [
             48, 130,   6, 211,   2,   1,   1,   2,   2,   3,   4,   4,
              2,  19,   1,   4,  32, 176,  72,  80, 167, 154, 110, 115,
             79, 231, 122, 236, 138,  59,  74,  79, 216, 171,  47,  69,
            126,  94, 176, 237, 191, 139,  23,  10,   1, 191, 144, 109,
            245,   4,  32, 171, 202,  47, 226, 246,   6, 189,  47, 114,
            171, 222, 168,  62, 131, 251,  62,  28, 144, 189,  51, 224,
             45, 114, 243, 105,  81, 240, 117,  15,  71,  58,  54, 161,
              6,   2,   4,  99,  93,  95,  31, 162,   4,   2,   2,  28,
             32, 163, 130,   5,
            ... 1651 more items
          ],
          port: 443,
          host: 'stream.bybit.com',
          path: null,
          headers: {
            'Sec-WebSocket-Version': 13,
            'Sec-WebSocket-Key': 'FB4eaNG0ubCgVvNa6NbsXg==',
            Connection: 'Upgrade',
            Upgrade: 'websocket',
            'Sec-WebSocket-Extensions': 'permessage-deflate; client_max_window_bits'
          },
          _defaultAgent: Agent {
            _events: [Object: null prototype],
            _eventsCount: 2,
            _maxListeners: undefined,
            defaultPort: 443,
            protocol: 'https:',
            options: [Object: null prototype],
            requests: [Object: null prototype] {},
            sockets: [Object: null prototype] {},
            freeSockets: [Object: null prototype] {},
            keepAliveMsecs: 1000,
            keepAlive: false,
            maxSockets: Infinity,
            maxFreeSockets: 256,
            scheduling: 'lifo',
            maxTotalSockets: Infinity,
            totalSocketCount: 0,
            maxCachedSessions: 100,
            _sessionCache: [Object],
            [Symbol(kCapture)]: false
          },
          servername: 'stream.bybit.com',
          _agentKey: 'stream.bybit.com:443:::::::::::::::::::::',
          encoding: null,
          singleUse: true
        },
        [Symbol(RequestTimeout)]: undefined
      },
      _error: null,
      url: 'wss://stream.bybit.com/spot/private/v3?api_key=aaaaaa&expires=1667063591282&signature=aaaaa',
      _req: null,
      [Symbol(kCapture)]: false
    },
    type: 'error',
    message: 'read ECONNRESET',
    error: Error: read ECONNRESET
        at TLSWrap.onStreamRead (node:internal/stream_base_commons:217:20) {
      errno: -4077,
      code: 'ECONNRESET',
      syscall: 'read'
    }
  }
}

**Comment by oDYRASH** [comment]
I gave you the whole error message because I don't know wich part you need :/

**Comment by tiagosiebler** [comment]
Please be careful when pasting errors - the url contained your api key. I've edited it, but anyone watching the repo will have seen it via email...

Regarding the error, did it reconnect automatically after you saw this error? Thanks

**Comment by oDYRASH** [comment]
> Please be careful when pasting errors - the url contained your api key. I've edited it, but anyone watching the repo will have seen it via email...
> 
> Regarding the error, did it reconnect automatically after you saw this error? Thanks

Okay thank for info !

No it stop reconnect, error occured after arnoud 2h30. the error crashed everythings. it does not reconnect after

**Comment by tiagosiebler** [comment]
> No it stop reconnect, error occured after arnoud 2h30. the error crashed everythings. it does not reconnect after

It should be more resilient than that, strange to hear this happen without further reconnects. Do you still have the full logs? 

Did you see this many times or only once? "Websocket error due to unexpected response error"

Were there any log messages containing `'Connection failed'` before or after this error? 

Lastly, do you see this happen a lot? I see a way I could handle this in the connector, but would be good if there's a way to confirm the fix worked.

**Comment by oDYRASH** [comment]
> > No it stop reconnect, error occured after arnoud 2h30. the error crashed everythings. it does not reconnect after
> 
> It should be more resilient than that, strange to hear this happen without further reconnects. Do you still have the full logs? 
> 
> Did you see this many times or only once? "Websocket error due to unexpected response error"
> 
> Were there any log messages containing `'Connection failed'` before or after this error? 
> 
> Lastly, do you see this happen a lot? I see a way I could handle this in the connector, but would be good if there's a way to confirm the fix worked.

I dis not see any 'connection failed'. I Saw it 2 Times, the the 2 Times I tried to let it run fro a longtime like many jours.

But it is now runing for 6h non stop and still dont have problem... 
I cant provide more infos due to the little periode I run my bot

**Comment by tiagosiebler** [comment]
Got it, thanks. Please let me know if it happens again. It's especially useful if you can check the logs again just before it happened, as there might be more context. I'll look to improve and test that part of the workflow in the meantime.

**Comment by oDYRASH** [comment]
Thé bot is still running for 14h non stop, error could Come from my code and crashed the whole program including websocket. I will tell you if anythings New Come out

**Comment by tiagosiebler** [comment]
Thanks again for reporting this. I found what probably caused the process to crash when you had a network error. The ws client rarely emits an 'error' event (e.g. if reconnect fails due to a network error). In node by default, if an event emitter emits an error event it's treated like an exception (unintentionally), which can cause a crash if you're not listening to the error event... 

I've added an error event listener by default, so this shouldn't happen again. I've also improved the reconnection workflow as well to remove another rare chance where reconnection may get stuck. I'm confident both of these will prevent your issue from happening again, but would certainly appreciate if you could help test this in the next release: #196
