### ISSUE TITLE
cannot fix reduce-only order qty

### ISSUE THREAD

**Issue by real-lazy-coder** [tiagosiebler/bybit-api#193]
I cannot seem to figure out why placing an order returns this error:

```json
{
    "ret_code": 130125,
    "ret_msg": "current position is zero, cannot fix reduce-only order qty"
}
```

Here is the code block:

```js
    const order = await client?.placeActiveOrder({
      side: 'Buy',
      symbol: 'BTCUSDT',
      order_type: 'Limit',
      qty: 0.01,
      price: 10000,
      time_in_force: 'GoodTillCancel',
      close_on_trigger: true,
      reduce_only: false,
      take_profit: 10500,
      stop_loss: 9500,
    })
```

Is there a setting I'm overlooking?

**Comment by tiagosiebler** [comment]
If you're looking to reduce a position, you should be using reduce only, not close on trigger, afaik. Some comments in the docs about this too:
https://bybit-exchange.github.io/docs/futuresV2/linear/#t-faq

If your intention was not to create a reduce-only style order, you should set both close on trigger & reduce only to false.

Some examples here for increasing and reducing a position in USDT perps (linear client): https://github.com/tiagosiebler/awesome-crypto-examples/blob/master/src/exchanges/bybit/orders/usdt-perp-orders.ts#L311-L320

**Comment by real-lazy-coder** [comment]
That makes total sense.  Thanks for the clarification.
