### ISSUE TITLE
Contract Client

### ISSUE THREAD

**Issue by real-lazy-coder** [tiagosiebler/bybit-api#195]
The documentation points to `https://github.com/tiagosiebler/bybit-api/blob/master/src/contract-client.ts` for Derivatives V3 Contract API's, but the file doesn't seem to exist.  It this still in work?  Do yo need any help?

**Comment by tiagosiebler** [comment]
Ah that's my mistake, I've started working on it but wanted to push out some other improvements in the meantime. Looks like the readme change slipped in prematurely! The REST client is done, but it's missing e2e tests and expansion of the ws client. Getting there, but distracted by other priorities!

**Comment by real-lazy-coder** [comment]
No worries.  Keep up the great work!

**Comment by tiagosiebler** [comment]
This is finished (#196) and will be available on npm shortly, as soon as the master branch finishes building. Thanks!
