### ISSUE TITLE
Error get ServerTime

### ISSUE THREAD

**Issue by tuwibu** [tiagosiebler/bybit-api#214]
Hi! 👋 
      
![photo_2023-01-04_20-38-28](https://user-images.githubusercontent.com/89235917/210760618-4b4a9729-924f-4137-9145-cfcccdc4301a.jpg)

Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `bybit-api@3.3.5` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/bybit-api/lib/linear-client.js b/node_modules/bybit-api/lib/linear-client.js
index cda2cff..64db5bc 100644
--- a/node_modules/bybit-api/lib/linear-client.js
+++ b/node_modules/bybit-api/lib/linear-client.js
@@ -24,8 +24,12 @@ class LinearClient extends BaseRestClient_1.default {
     }
     fetchServerTime() {
         return __awaiter(this, void 0, void 0, function* () {
-            const timeRes = yield this.getServerTime();
-            return Number(timeRes.time_now);
+            try {
+                const timeRes = yield this.getServerTime();
+                return Number(timeRes.time_now);
+            } catch (ex) {
+                return new Date().getTime() / 1000;
+            }
         });
     }
     /**
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by tiagosiebler** [comment]
Hi,

Glad you're enjoying my work. Unless everyone including myself is seeing a timeout, a timeout suggests a network issue on your end. I would suggest checking why your environment can't make a simple GET request to https://api.bybit.com/v2/public/time

Maybe you also see timeouts when using other tools, such as CURL?
