### ISSUE TITLE
Request parameter error

### ISSUE THREAD

**Issue by Savchuk** [tiagosiebler/bybit-api#217]
const client = new CopyTradingClient({
                    key: API_KEY,
                    secret: API_SECRET,
                    testnet: useTestnet
                },
                // requestLibraryOptions
            );

            client.submitOrder(params).then(console.log)

Params:
{
  side: 'Sell',
  symbol: 'ETHUSDT',
  qty: 0.2,
  orderType: 'Limit',
  price: 1261.15
}

Response:
{
  retCode: 10001,
  retMsg: 'Request parameter error.',
  result: {},
  retExtInfo: {},
  time: 1673189191295
}

Could you suggest what is the cause of the error?
Thank you

**Comment by tiagosiebler** [comment]
Quantity and price should be sent as strings:
https://github.com/tiagosiebler/bybit-api/blob/master/src/types/request/copy-trading.ts#L8-L9
https://bybit-exchange.github.io/docs/copy_trading/#t-ct_order

I do recommend trying out TypeScript - I try to add as many types as I can and the request params for this method have types defined (first link). TypeScript can catch that error before even running the code - example how it looks:
<img width="546" alt="Screenshot 2023-01-09 at 10 46 19" src="https://user-images.githubusercontent.com/14090872/211290888-d7c21157-fe80-4af5-a0fa-6a9dbc680edf.png">

And if I hover over the error:
<img width="988" alt="Screenshot 2023-01-09 at 10 46 25" src="https://user-images.githubusercontent.com/14090872/211290916-532ec86f-dc11-44d5-bf9d-e223b3e3b83a.png">

Number not assignable to string, which would make me either try a string or check the docs if this should indeed be a string.
