### ISSUE TITLE
WebsocketClient cannot subscribe to unifiedPerp market with publicTrade.(USDC pairs) topics

### ISSUE THREAD

**Issue by wizard50** [tiagosiebler/bybit-api#220]
https://github.com/tiagosiebler/bybit-api/blob/b1e23f2d05cbb93fdeeca40de7ba959b66a96e3b/src/util/websocket-util.ts#L279

This check fails because USDC pairs do not contain "USDC" but "PERP". 

For example "BTCPERP"

**Comment by tiagosiebler** [comment]
That's a good catch, thanks for reporting this. Will be fixed shortly in v3.3.10 via #221 as soon as it's merged and the CI run finishes. Let me know if you notice anything else!

**Comment by tiagosiebler** [comment]
v3.3.10 is now on npm. Let me know if you notice anything else. Thanks!
