### ISSUE TITLE
To finding account is unified or not 

### ISSUE THREAD

**Issue by MuratKaragozgil** [tiagosiebler/bybit-api#228]
Hello guys,

First of all, thank you for this open source project and all maintain.

My question is how can I understand if the account is upgraded to unified or not?  Currently I'm using the linear api to open and close positions with some api keys. But some accounts have been upgraded to unified and now i can't get wallet balances of these api keys. I tried to get wallet balance with UnifiedClient and yes its working...

Now i want to understand which keys are unified and not.

Thanks,
Murat

**Comment by tiagosiebler** [comment]
Afaik the only way is to try one of the non-unified endpoints OR there's a new property in one of the V5 endpoints:
https://bybit-exchange.github.io/docs/v5/account/account-info

I'm still working on the V5 endpoints, but if you'd like to try it early I can push out a beta release on Monday? PR with progress so far, if you'd like to follow: #224

**Comment by MuratKaragozgil** [comment]
Amazing explanation and a good workaround, thanks a lot!
