### ISSUE TITLE
Issue while merging from V3 to V5

### ISSUE THREAD

**Issue by titi-devv** [tiagosiebler/bybit-api#231]
Yo guys!
I'm merging my code to the V5 API but met an error and can't find a fix :/
It was working well with the V3.
I'm opening a new order and then want to modify the leverage, but got an error.

Here is my code : 

```
placeActiveOrder(
      {
        category: 'linear',
        side: calledTrade.type,
        symbol: calledTrade.pair,
        orderType: 'Market',
        qty: calledTrade.qty.toString(),
        timeInForce: 'GTC',
        stopLoss: calledTrade.stopLoss.toString(),
        reduceOnly: false,
        closeOnTrigger: false,
        positionIdx: 0
      },
      client
    ).then((msg: APIResponseV3WithTime<any>) => {
      if (isOrderSubmitted(msg, trade, member, 'opening')) {
        const orderId = msg.result.orderId;
        updateOrderId(calledTrade, orderId, member.id, trade);
      }
    });
    console.log(calledTrade.pair, calledTrade.leverage.toString());
    setUserLeverage(
      {
        category: 'linear',
        symbol: calledTrade.pair,
        buyLeverage: calledTrade.leverage.toString(),
        sellLeverage: calledTrade.leverage.toString()
      },
      client
    ).then((msg: APIResponseV3WithTime<any>) => {
      console.log(msg);
      if (msg.retCode !== 0 && msg.retCode !== 34036) {
        console.log(
          `${member.name}: Error with ${trade.pair} leverage: \n ${msg.retCode}: ${msg.retMsg}`
        );
      }
    });
```

The order is well opened, but when i'm trying to setUserLeverage i receive this error: 
```
{
  retCode: 10004,
  retMsg: 'error sign! origin_string[1677614447573rNcDCdnxbBcP4Th4sg5000{"category":"linear","symbol":"AUDIOUSDT","buyLeverage":"8","sellLeverage":"8"}]',
  result: {},
  retExtInfo: {},
  time: 1677614447972
}


```
Do you have anidea from where this issue could come?

**Comment by tiagosiebler** [comment]
Strange, this is working in the e2e test:
https://github.com/tiagosiebler/bybit-api/blob/master/test/v5/private.write.test.ts#L182-L187

The sign error would suggest a problem with the request (aka what the connector is doing to build the request), but then the test wouldn't pass...I'll try to run the tests again in case anything chanced since then.

**Comment by tiagosiebler** [comment]
Nope, tests look OK - no sign errors there:
<img width="414" alt="Screenshot 2023-02-28 at 20 31 34" src="https://user-images.githubusercontent.com/14090872/221971745-56dd5207-0ece-4dc7-9e36-ecbc89ad6691.png">

I need some way to reproduce this issue on my end..hmm

**Comment by tiagosiebler** [comment]
Wait, my test is with the `RestClientV5`, the method is called `setLeverage` on the v5 rest client - e.g:
```
      const result = await api.setLeverage({
        category: 'linear',
        buyLeverage: '8',
        sellLeverage: '8',
        symbol: 'AUDIOUSDT',
      });

      console.log('result: ', result);
```

What rest client are you having problems with?

**Comment by titi-devv** [comment]
Thanks for your fast answer!!

Unfortunately, I'm using RestClientV5, like this: 

```
const setUserLeverage = async (
  params: SetLeverageParamsV5,
  client: RestClientV5
) => {
  let msg: APIResponseV3WithTime<any>;
  await client.setLeverage(params).then((result) => {
    msg = result;
  });
  return msg;
};
```

Everything should be the same as the V3 right?

**Comment by titi-devv** [comment]
My bad error was on my end, the setLeverage function was not waiting for the placeActiveOrder, that's why I got my error. Just had to add an await. Weird that i's was working well on the V3.
Anyway, I'm closing this issue, big thanks !

**Comment by tiagosiebler** [comment]
> Thanks for your fast answer!!
> 
> Unfortunately, I'm using RestClientV5, like this:
> 
> ```
> const setUserLeverage = async (
>   params: SetLeverageParamsV5,
>   client: RestClientV5
> ) => {
>   let msg: APIResponseV3WithTime<any>;
>   await client.setLeverage(params).then((result) => {
>     msg = result;
>   });
>   return msg;
> };
> ```
> 
> Everything should be the same as the V3 right?

Glad you found the problem! Btw, small unsolicited tip if I may, instead of what you posted:
```
const setUserLeverage = async (
  params: SetLeverageParamsV5,
  client: RestClientV5
) => {
  let msg: APIResponseV3WithTime<any>;
  await client.setLeverage(params).then((result) => {
    msg = result;
  });
  return msg;
};

setUserLeverage(
  {
    category: 'linear',
    symbol: calledTrade.pair,
    buyLeverage: calledTrade.leverage.toString(),
    sellLeverage: calledTrade.leverage.toString()
  },
  client
).then((msg: APIResponseV3WithTime<any>) => {
  console.log(msg);
  if (msg.retCode !== 0 && msg.retCode !== 34036) {
    console.log(
      `${member.name}: Error with ${trade.pair} leverage: \n ${msg.retCode}: ${msg.retMsg}`
    );
  }
});
```

You could do this:
```typescript
try {
  const setLeverageResult = await client.setLeverage({
      category: 'linear',
      symbol: calledTrade.pair,
      buyLeverage: calledTrade.leverage.toString(),
      sellLeverage: calledTrade.leverage.toString()
  });

  if (setLeverageResult.retCode !== 0 && setLeverageResult.retCode !== 34036) {
    throw setLeverageResult;
  }

  console.log(setLeverageResult);
} catch (e) {
  if (e.retCode) {
    console.log(
      `${member.name}: Error with ${calledTrade.pair} leverage: \n ${e.retCode}: ${e.retMsg}`
    );
  } else {
    // some other exception (e.g. network err)
  }
}
```

Reason for this:
- all error handling in catch block, including anything thrown (like network errors)
- no mixing of await/then - if you're using await, technically you shouldn't need `then` anymore

If you wanted to keep your setUserLeverage fn for other reasons, you could also just return it directly instead of the mix of await and then:
```typescript
const setUserLeverage = async (
  params: SetLeverageParamsV5,
  client: RestClientV5
) => {
  return client.setLeverage(params)
};
```

That will give the same result without stripping the type returned by the restclient's setLeverage function. Hope this helps

**Comment by titi-devv** [comment]
Thank you so much @tiagosiebler, didn't expect that much! 
I will update my code with your suggestions. Always improving
