### ISSUE TITLE
Get Balance Response wrong type 

### ISSUE THREAD

**Issue by MatheoG** [tiagosiebler/bybit-api#233]
There is an error with the response of getWalletBalance function
it's:
`
 getWalletBalance(params: GetWalletBalanceParamsV5): Promise<APIResponseV3WithTime<WalletBalanceV5>>;
`
it should be : 
`
    getWalletBalance(params: GetWalletBalanceParamsV5): Promise<APIResponseV3WithTime<{list: WalletBalanceV5[]}>>;
`

because the response of getWalletBalance function is:
![image](https://user-images.githubusercontent.com/56150287/222757811-ecf7ca2f-a5d3-47bf-bc4d-e9afb3a5a0d2.png)

**Comment by tiagosiebler** [comment]
Thanks, will be fixed shortly in v3.5.2: #234

**Comment by tiagosiebler** [comment]
Thanks @MatheoG - v3.5.2 has been released. If you notice anything else, please feel free to open a new issue. PRs also welcome.
