### ISSUE TITLE
Process does not exit with "enable_time_sync: true"

### ISSUE THREAD

**Issue by Tindtily** [tiagosiebler/bybit-api#235]
Once 'enable_time_sync: true' is used, the program will not close, it will get stuck at the end. Once removed, the program will close normally
```
const client = new RestClientV5({
  key: apiKey,
  secret: apiSec,
  enable_time_sync: true
}, {
  httpsAgent: agent
})

async function getRealTimeOrders(){
  let result = await client.getActiveOrders({
    category: "linear",
    symbol:"BTCUSDT"
  })
  logger.debug("result：", JSON.stringify(result))
  return result
}
getRealTimeOrders()
```
Any other request, not just the active API, will cause the same problem. It may be that the impl of the sync time has some bug, please check!

**Comment by tiagosiebler** [comment]
If you use the "time sync" feature, the REST client will set a timer (setInterval) which will keep your process alive even after you've finished making API calls.

Generally speaking, I would **not** recommend using enable_time_sync at all. In my experience with the current design of the time sync feature, it can cause more problems than it solves. One unusually slow request can create an unusual offset that suddenly breaks every timestamp used until the next sync attempt, causing recv window errors instead of solving them.

This is the reason I disabled it by default some time ago - it used to be enabled by default. This is especially if you're executing workflows where you don't expect the process to live for very long. If you're having recv window errors without the time sync feature, you should ensure your system clock is in sync with a time service. 

Lots of information about this here: https://github.com/tiagosiebler/awesome-crypto-examples/wiki/Timestamp-for-this-request-is-outside-of-the-recvWindow

**Comment by Tindtily** [comment]
> 

i checked the impl, why not only keep the synctime without the interval?

**Comment by tiagosiebler** [comment]
> i checked the impl, why not only keep the synctime without the interval?

You could, but that might defeat the original intended point of this feature - regularly checking for a larger drift between system and server time. If you want to simulate behaviour like this, you could call syncTime(true) to force this behaviour as a one off. If you wanted to try that, would need to make a small change to make syncTime a public method. I'll review the PR if you want this - but I do want to emphasise the importance of running OS level time sync via a service like ntp to ensure this isn't even needed.

**Comment by tiagosiebler** [comment]
Closing this, but if further questions arise, feel free to reopen or make a new issue. Thanks

**Comment by Tindtily** [comment]
I have been very annoyed by this time problem these days. I found that you don't actually need a timer to synchronize the time. You only need to synchronize the time during initialization and when you encounter a time error. Because the time error codes of different versions of the api are different, each client instance class needs to implement a separate method `shouldSyncTime(response)`to check whether the time needs to be synchronized.
e.g.
```
async function axiosCall(options) {
  try {
    const response = await axios(options);
    if (response.status == 200) {
      return response.data;
    } else if (this.shouldSyncTime(response)) {
      await this.syncTime();
      return await this.axiosCall(options);
    }
    throw response;
  } catch (e) {
    return this.parseException(e);
  }
}
```
```
// RestClientV5  
//...
shouldSyncTime(response){
  return response.retCode === 10002
}
//...
```

**Comment by Tindtily** [comment]
I found the  `prepareSignParams` function in `BaseRestClient.ts`  has one syncTime call. Why not set a flag to turn on mandatory syncTime so the user can choose whether or not to syncTime precedes each private request. 
Now I have changed the local node_moudles manually, I hope you can refer to my opinion. It won't take long if you synchronize the time each time you send a private request

**Comment by Tindtily** [comment]
> but I do want to emphasise the importance of running OS level time sync via a service like ntp to ensure this isn't even needed.

I have tried to synchronize the time through ntp, but the problem still persists

**Comment by tiagosiebler** [comment]
> I found the `prepareSignParams` function in `BaseRestClient.ts` has one syncTime call. Why not set a flag to turn on mandatory syncTime so the user can choose whether or not to syncTime precedes each private request. Now I have changed the local node_moudles manually, I hope you can refer to my opinion. It won't take long if you synchronize the time each time you send a private request

It would essentially double the chances of running into rate limits, but I'm not against an optional feature that's disabled by default. 

> You only need to synchronize the time during initialization and when you encounter a time error.

This does seem like a really good point!

**Comment by Tindtily** [comment]
@tiagosiebler  Is there anything wrong with my pr #247 ? I hope it can be merged as soon as possible. My project is still running, and the code is still modified manually at present.  Otherwise, I'd have to fork one.

**Comment by tiagosiebler** [comment]
> @tiagosiebler Is there anything wrong with my pr #247 ? I hope it can be merged as soon as possible. My project is still running, and the code is still modified manually at present. Otherwise, I'd have to fork one.

sorry for the delay, will review properly tomorrow
