### ISSUE TITLE
wrong types

### ISSUE THREAD

**Issue by tony-riotracers** [tiagosiebler/bybit-api#237]
several types are wrong; for example, price and stopLoss are supposed to be strings, not numbers.

https://github.com/tiagosiebler/bybit-api/blob/f59438d1adf3090408f852f4cbc4f1811bcff139/src/types/request/linear.ts#L55

https://bybit-exchange.github.io/docs/derivatives/unified/place-order

**Comment by tiagosiebler** [comment]
Discussed over here: https://github.com/tiagosiebler/bybit-api/pull/238#issuecomment-1467921270

These types are for the v2 linear (USDT Perp) APIs, while the link is for the unified margin APIs (which are available via the unified margin client).
