### ISSUE TITLE
Orderbook only working in linear market, without V5.

### ISSUE THREAD

**Issue by dasbts** [tiagosiebler/bybit-api#246]
Hello, 

I am fetching the orderbook through linear, and thought I would migrate to V5 to use more functionality and keep up to date with Bybit. However, it seems like I can only get out the orderbook from WS by for example ws.subscribe('orderBook**L2_**25.DOGEUSDT'); which I happened to find as documented example in the separate orderbook NPM library that you have. 

If I do ws.subscribe('orderBook.25.'+message); as described in the examples and in the code, I get nothing. If I try market: 'V5' and then change to ws.subscribeV5('orderBook.25.'+message, 'linear'); or ws.subscribeV5('orderBookL2_25.'+message, 'linear'); I don't get any output at all. 

Also I am interested in USDT derivatives, but it seems like I can only get linear at all so far, using what I think is Bybit V2 API by specifying market: 'linear'. 

I have tried searching but cannot find, am I configuring it incorrectly?

**Comment by dasbts** [comment]
Also can't seem to get kline to work at all in my websocket. I use the most recent "npm install --save bybit-api" by the way.

**Comment by tiagosiebler** [comment]
Hi @dasbts 

The topics are defined in the API docs, they're likely all different to what they were in the pre-V5 endpoints:
https://bybit-exchange.github.io/docs/v5/websocket/public/orderbook

For linear, try this:
```
ws.subscribeV5('orderbook.1.BTCUSDT', 'linear');
```

Here's klines:
https://bybit-exchange.github.io/docs/v5/websocket/public/kline

E.g.

```
ws.subscribeV5('kline.30.BTCUSDT', 'linear');
```

**Comment by dasbts** [comment]
Hi Tiago,

Thanks for the information.

Yeah, I believe that is what I tried. Can of course give it some more tests during this week, but have to prioritize work.

**Comment by dasbts** [comment]
Any ideas? I use this: 
  bybitws = new WebsocketClient({
    livenet: true,
    key: apiKey,
    secret: apiSecret,
    market: 'linear',
  });

From that, as mentioned, only this seem to work: 
bybitws.subscribe('orderBookL2_25.DOGEUSDT')

**Comment by dasbts** [comment]
Spent a lot of time trying to figure it out, but the documentation when comparing on Bybit for the V3 and V5 API has different info than your documentation, the output is different from the approach of L2 where I used const { OrderBooksStore, OrderBookLevel } = require('orderbooks'); as well as handleOrderbookUpdate and handleDelta. 

I get very different outputs, where the L2 one seem to be complete concatenated into the delete, update, insert keys. The new version seem to give me multiple different sizes for same price. How is it possible to use this with your orderbook library? Because in the linear websocket for L2, we had delete, update, insert already made, in the V5 I have no clue what is supposed to be deleted from the orderbook, and what is supposed to be the updated ones. 

This is the example I have used as inspiration, but as mentioned, I don't know if it still works. 
https://github.com/tiagosiebler/orderbooks/blob/HEAD/samples/bybit.js

**Comment by dasbts** [comment]
This is the new output format: 
{
  s: 'ETHUSDT',
  b: [
    [ '1735.73', '213.55' ],
    [ '1735.72', '16.74' ],
    [ '1735.71', '0' ],
    [ '1735.70', '0' ],
    [ '1735.36', '10.39' ],
    [ '1735.15', '20.77' ],
    [ '1735.06', '25.27' ],
    [ '1735.05', '25.70' ],
    [ '1735.00', '158.08' ],
    [ '1734.99', '204.38' ]
  ],
  a: [
    [ '1735.74', '9.55' ],
    [ '1736.09', '9.23' ],
    [ '1736.14', '14.41' ],
    [ '1736.25', '16.56' ],
    [ '1736.28', '0' ],
    [ '1736.29', '32.30' ],
    [ '1736.33', '7.51' ],
    [ '1736.39', '19.03' ],
    [ '1736.40', '11.61' ],
    [ '1736.42', '37.84' ]
  ],
  u: 135218156,
  seq: 71940764212
}

Even if V3 API is saying the same output parameters as V5 in the official Bybit docs, the L2 orderbook returns that delete, insert, update, and I can't seem to get L2 to work with V5.

**Comment by dasbts** [comment]
Nevermind, figured it out. Either it was fixed in an update as I just updated, or I was just writing it wrong..

**Comment by tiagosiebler** [comment]
> This is the example I have used as inspiration, but as mentioned, I don't know if it still works. https://github.com/tiagosiebler/orderbooks/blob/HEAD/samples/bybit.js

Ah yes, this example is somewhat old now and needs to be updated for the v5 bybit websockets. Did you get the V5 websockets working with the orderbooks module? Would love to add an example to the orderbooks repo, a PR would be appreciated but I can also add it myself if you were to just send an example here - since it's probably <100 lines! 

Thanks!

**Comment by caiusCitiriga** [comment]
> This is the new output format: { s: 'ETHUSDT', b: [ [ '1735.73', '213.55' ], [ '1735.72', '16.74' ], [ '1735.71', '0' ], [ '1735.70', '0' ], [ '1735.36', '10.39' ], [ '1735.15', '20.77' ], [ '1735.06', '25.27' ], [ '1735.05', '25.70' ], [ '1735.00', '158.08' ], [ '1734.99', '204.38' ] ], a: [ [ '1735.74', '9.55' ], [ '1736.09', '9.23' ], [ '1736.14', '14.41' ], [ '1736.25', '16.56' ], [ '1736.28', '0' ], [ '1736.29', '32.30' ], [ '1736.33', '7.51' ], [ '1736.39', '19.03' ], [ '1736.40', '11.61' ], [ '1736.42', '37.84' ] ], u: 135218156, seq: 71940764212 }
> 
> Even if V3 API is saying the same output parameters as V5 in the official Bybit docs, the L2 orderbook returns that delete, insert, update, and I can't seem to get L2 to work with V5.

Very similar to binance's response. When you find a price level with 0 amount, it means that the level should be removed from the local book
