### ISSUE TITLE
invalid request, please check your server timestamp or recv_window param

### ISSUE THREAD

**Issue by mmaestrini** [tiagosiebler/bybit-api#260]
Hi Tiago

I have been making good progress thanks to your library.

However, after i went to dinner and came back to coding I get the following error: invalid request, please check your server timestamp or recv_window param. req_timestamp[1683929882141],server_timestamp[1683929880902],recv_window[5000]'

I read a bit about it but i didnt find antyhing actionable to fix it. Nothing change code wise on my end. Also I do have a GB connection so i doubt that the case. My mac is a bit slow these days, but i mean again, i doubt this can be the issue. What's the deal? I tried increasing the window but no luck. 

Any help would be greatly appreciated.

**Comment by mmaestrini** [comment]
Turned out that resynching my mac time seemed to  have fixed it...

**Comment by tiagosiebler** [comment]
Glad you found the solution already. It is indeed tied to your system clock - more info about this here: https://github.com/tiagosiebler/awesome-crypto-examples/wiki/Timestamp-for-this-request-is-outside-of-the-recvWindow
