### ISSUE TITLE
Passing "qty" to amendOrder returns error from Bybit

### ISSUE THREAD

**Issue by ralvs** [tiagosiebler/bybit-api#269]
Hey guys, not sure if this is a "problem" from this library but, as you have contacts inside Bybit, maybe you could help me. Please!

If I open an order (submitOrder) with `qty = 7.30380801`, for example
Then later, I call amendOrder with `qty = 7.30381433`, notice that it's slightly different from the original order.
This returns the error from Bybit:

    {
        status: 'fulfilled',
        value: {
          retCode: 10001,
          retMsg: 'params error: qty err',
          result: {},
          retExtInfo: {},
          time: 1687220916546
        }
    }

Doesn't make any sense for me that I have to pass a different `qty` as is explained in the API documentation

    qty | false | string | Order quantity after modification. Do not pass it if not modify the qty

But, even numbers with a small difference cause the error.
What can we do?

**Comment by tiagosiebler** [comment]
Which rest client are you using, v5? Can you provide an example request? Maybe it's precision related and any decimals after the 3038 are ignored?

**Comment by ralvs** [comment]
Yes, using v5.
About the precision, I'm using 8 decimals because is the maximum accepted by Bybit, and can't use less because of the coins that has very small values.

An example of an order of the exact same `qty`

    params: {
      category: 'linear',
      symbol: 'LTCUSDT',
      orderType: 'Limit',
      orderLinkId: '11046772-0473-4683-873e-847158dbf7f2',
      price: '75.13',
      qty: '2.45692542',
      side: 'Buy',
      stopLoss: '0.00',
      takeProfit: '0.00',
      reduceOnly: false
    }


Answer


    result: {
      retCode: 10001,
      retMsg: 'params error: qty err',
      result: {},
      retExtInfo: {},
      time: 1687378236296
    }

**Comment by tiagosiebler** [comment]
Hi @ralvs 

According to this
https://api.bybit.com/v5/market/instruments-info?category=linear&symbol=LTCUSDT

Qty step is "0.1". So the qty should always be fixed at 1 decimal places.

The endpoint for placing an order does not limit the qty precision and it will be automatically converted to 1 decimal place, but for the amend endpoint it's important to use the correct precision or this error will happen (which I agree could be more valuable if it suggested it's a precision issue). Can you try this?

**Comment by ralvs** [comment]
Hi @tiagosiebler 
Sorry for the delay, lasts days have been busy

Ok, so there is a 'qty step' for each coin. 
But this "complicates" things, as to execute an Amend, I need another api request to get this 'qty step' of the coin.

And doesn't make sense that Bybit ignores this on Submit but not on Amend !
Could you please pass this along to Bybit?

A workaround that I will try is to get this info of every coin and keep it in a variable in my script
https://api.bybit.com/v5/market/instruments-info?category=linear&basecoin=USDT

**Comment by tiagosiebler** [comment]
> And doesn't make sense that Bybit ignores this on Submit but not on Amend ! Could you please pass this along to Bybit?

I do agree and already mentioned this to Bybit as well.

> A workaround that I will try is to get this info of every coin and keep it in a variable in my script https://api.bybit.com/v5/market/instruments-info?category=linear&basecoin=USDT

This is actually common on major exchanges. Typically these per-coin rules don't change frequently, so you can maintain a local cache of the rules returned by the instruments info endpoint (e.g. in a variable). Just make sure to regularly refresh this cache.

**Comment by ralvs** [comment]
Great @tiagosiebler, thanks for the help again 😊

I have just implemented this "cache" and works fine.
