### ISSUE TITLE
100% Fee Discount for 30 Days. Apply within.

### ISSUE THREAD

**Issue by tiagosiebler** [tiagosiebler/bybit-api#271]
Algo traders! Exciting announcement with Bybit! In recognition of our growing community, Bybit have generously offered a fee discount promotion for our growing community of traders & devs! How can you take part? 

Fill in the google form with your account UID & email and Bybit will apply a 30 day 100% maker fee discount to your account:
https://forms.gle/kat45fA56b4ky7Wm9

Form submissions will be passed on to bybit in batches. Furthermore - WSOT is around the corner and we will have a team squad for our community! Stay tuned for more details when the time comes!

Don't forget to join our growing community of dev-traders in telegram. Meet likeminded devs, collaborate & network:
https://t.me/nodetraders

**Comment by brlocky** [comment]
@tiagosiebler is there other platforms ? other then Telegram ?

**Comment by tiagosiebler** [comment]
> @tiagosiebler is there other platforms ? other then Telegram ?

Hey @brlocky , only telegram at the moment
