### ISSUE TITLE
startTime and endTime support for order history. API QUESTION

### ISSUE THREAD

**Issue by AlexK020908** [tiagosiebler/bybit-api#272]
For  /v5/order/history, the current request parameters in the API does not support startTime and endTime illustrated here: https://bybit-exchange.github.io/docs/v5/order/order-list

I added these parameters in GetAccountOrdersParams, but the request returns an error code: 
```
{
    "retCode": 10001,
    "retMsg": "params error: startTime or endTime is needed",
    "result": {},
    "retExtInfo": {},
    "time": 1687841830995
}
```

The code I ran: 
```
this.client.getHistoricOrders({
      category: category,
      startTime: startTime,
      endTime: endTime,
      limit: limitPerPage,
      orderStatus: "Filled"
    })
      .then((result: any) => {
        fs.writeFileSync(tradeHistoryOutputPath, JSON.stringify(result));
      })
      .catch((err: any) => {
        throw err;
      })
```

the updated parameters: 
```
export interface GetAccountOrdersParams {
    category: CategoryV5;
    symbol?: string;
    baseCoin?: string;
    settleCoin?: string;
    orderId?: string;
    orderLinkId?: string;
    openOnly?: 0 | 1 | 2;
    orderFilter?: OrderFilterV5;
    startTime?: number,   // I added this
    orderStatus?: string,   // I added this
    endTime?: number,   // I added this
    limit?: number;
    cursor?: string;
}
```
Is this to be included as part of the API anytime soon?

**Comment by tiagosiebler** [comment]
Hi @AlexK020908 

Thanks for raising this. Are you on the latest version of this SDK? Looking at the rest client v5 implementation, there's some naming inconsistency I will fix shortly, but otherwise it does point to GetAccountHistoricOrdersPArams (shortly will be renamed to GetAccountHistoricOrdersParamsV5):
https://github.com/tiagosiebler/bybit-api/blob/master/src/rest-client-v5.ts#L411

Looking at the definition of that interface, it already includes these 3 parameters:
https://github.com/tiagosiebler/bybit-api/blob/master/src/types/request/v5-trade.ts#L84

**Comment by AlexK020908** [comment]
@tiagosiebler  ah thanks for this I might not be on the latest version. 

To get the latest I will just have to re install this dependency is that correct? 

Thanks!

**Comment by tiagosiebler** [comment]
@AlexK020908 should work, you can check your package.json to see which version it has after reinstalling it (`npm install bybit-api`).

Worst case, if it doesn't update to the latest version you can also force it with `npm install bybit-api@latest`.

**Comment by AlexK020908** [comment]
@tiagosiebler I downloaded the most recent version and I am still getting the same response code: 
The code I ran: 

```Javascript
  public GetTradeHistory(category: CategoryV5, tradeHistoryOutputPath: string, startTime: number, limitPerPage: number, currResult: Array<any>, cursor: string, iteration: number, endTime: number): Promise<void> {

    return this.client.getHistoricOrders({
      category: category,
      startTime: startTime,
      endTime: endTime,
      limit: limitPerPage,
      orderStatus: "Filled"
    })
      .then((result: any) => {
        fs.writeFileSync(tradeHistoryOutputPath, JSON.stringify(result));
      })
      .catch((err: any) => {
        throw err;
      })
  }
```
Please ignore the extra params, they are used for future recursions to get all results since startTime 0. Right now, a single request given startTime and endTime, does not work, I am not sure why...(even though I've specified both start and endTime)

The main function
``` Javascript
async function main() {
    let fetcher: BybitDataFetcher = new BybitDataFetcher();
    await fetcher.GetTradeHistory("linear", "./RequestOutputs/tradeHistory.json", 0, 100, [], "", 0, Date.now());
}
```

response: 
``` JSON
{"retCode":10001,"retMsg":"params error: startTime or endTime is needed","result":{},"retExtInfo":{},"time":1687915427093}
```

I don't think I did anything wrong, could you please check if you have this issue when you have some time?
My version is: "bybit-api": "^3.7.1"

**Comment by tiagosiebler** [comment]
Ahh my first attempt was a success, tested with spot, but then I tried linear and I got the same error. Looking at the docs, check the description on `startTime`:
```
The start timestamp (ms)
Normal spot is not supported temporarily
startTime and endTime must be passed together
If not passed, query the past 7 days data by default
```

So then I adapted my code to make endTime automatically be my startTime + 7 days:
```typescript

    const daysInMs7 = 7 * 24 * 60 * 60 * 1000; // + 7 days
    const someDate = new Date('2022-09-16 04:33:02').getTime();
    const historicOrders = await client.getHistoricOrders({
      category: 'linear',
      startTime: someDate,
      endTime: someDate + daysInMs7,
      limit: 50,
      orderStatus: 'Filled',
    });
    console.log('historicOrders: ', historicOrders);
```

Can you try a more constrained time range? Might be a problem that your start time is 0.

**Comment by AlexK020908** [comment]
@tiagosiebler Thanks, I will try this and see if it works.

**Comment by AlexK020908** [comment]
@tiagosiebler This worked, it's quite odd that the interval can not exceed 7 days... Thanks for your help!

It doesn't explicitly say it can't exceed 7 days on the docs....

**Comment by tiagosiebler** [comment]
> @tiagosiebler This worked, it's quite odd that the interval can not exceed 7 days... Thanks for your help!
> 
> It doesn't explicitly say it can't exceed 7 days on the docs....

True, maybe it's not the 7 days but the fact you sent 0 as the start time?

**Comment by AlexK020908** [comment]
> > @tiagosiebler This worked, it's quite odd that the interval can not exceed 7 days... Thanks for your help!
> > It doesn't explicitly say it can't exceed 7 days on the docs....
> 
> True, maybe it's not the 7 days but the fact you sent 0 as the start time?

Yes that is why, if I changed to an actual date, it worked, but still, I can only query based on 7 day intervals. I think it may be useful to note that down.

**Comment by tiagosiebler** [comment]
> Yes that is why, if I changed to an actual date, it worked, but still, I can only query based on 7 day intervals. I think it may be useful to note that down.

Makes sense, I've passed on your feedback to bybit - perhaps they can improve the docs here. Thanks!
