### ISSUE TITLE
Custom header ignored

### ISSUE THREAD

**Issue by milanpredic** [tiagosiebler/bybit-api#274]
https://github.com/tiagosiebler/bybit-api/blob/f8be8a6279a77c5312a2dc44b5ce5d68d70e3600/src/util/BaseRestClient.ts#L125C4-L132C9

Custom header is ignored:

`new RestClientV5({
            key: config.apiKey,
            secret: config.apiSecret
        }, {
            headers: {
                'x-some-header': 'some-header-value'
            }
        })`

**Comment by tiagosiebler** [comment]
Not supported right now, but happy to discuss the use case if there's still need for it

**Comment by carlsachs** [comment]
I have a need for this to input the broker ID into my requests, unless there is a different way? @tiagosiebler 

My only option I see as of now is reworking my client to work with the rest API vs the client.

**Comment by carlsachs** [comment]
@tiagosiebler I am having some trouble adding my x-referer to my current client, which utilizes the RestClientV5, can I just add it as headers in my constructor where I initialize the client?
