### ISSUE TITLE
Bybit does give api users access to "trade history"

### ISSUE THREAD

**Issue by AlexK020908** [tiagosiebler/bybit-api#278]
Currently, we can only access "Order history" through /v5/order/history, but can't really access "trade history", there aren't any explicit docs on it and I can not find an API call for it as well. 

The reason why i like to access trade history is because the fill/total is listed very clearly, so I can get the start and end time of a contract. For example, opened short for SOLusdt at .... and closed at ..... with PNL of 2 dollars.

I might be missing something, does anyone know how to query trade history?

![image](https://github.com/tiagosiebler/bybit-api/assets/96352305/20f57cd8-293d-4e9b-bd0b-6bd5029befae)

The reason why I want this is because I want the "startTime" and the "endTime" of a trade that went through open -> closed. 

Is this possible given the current API?

**Comment by tiagosiebler** [comment]
Is this perhaps more in the direction of what you're looking for?
https://bybit-exchange.github.io/docs/v5/position/execution

**Comment by tiagosiebler** [comment]
Closing this. Feel free to reopen if you think something is missing.
