### ISSUE TITLE
Spot limit order

### ISSUE THREAD

**Issue by Cyrilouletouriste** [tiagosiebler/bybit-api#282]
Hi !

Nice job, your module is nice, but i met a problem creating a spot, limit order  (using V5 client) :

`
async function buy(category,symbol,ordertype,qty,side,price)
{
  try {
    const RestClient = new RestClientV5({
      key: API_KEY,
      secret: PRIVATE_KEY,
    });
    var buyOrderResult = await RestClient.submitOrder({category:category,symbol:symbol,side:side,positionIdx:0,orderType:ordertype,qty:qty,price:price,timeInForce:"GTC"});
    console.log('buyOrderResult:', buyOrderResult);
  } catch (e) {
    console.error('request failed: ', e);
  }
}
`

Here is the data sent by the module : 
`{
  category: 'spot',
  symbol: 'BTCUSDT',
  side: 'Buy',
  positionIdx: 0,
  orderType: 'Limit',
  qty: 0.0002,
  price: '29436.01',
  timeInForce: 'GTC'
}`

Return :

`buyOrderResult: {
  retCode: 10001,
  retMsg: 'Request parameter error.',
  result: {},
  retExtInfo: {},
  time: 1691862125487
}`

The strangest thing is that sometimes, the orders are working fine, any idea ? Thanks !

**Comment by Cyrilouletouriste** [comment]
I fixed the problem, i set wrong quantity :)

**Comment by tiagosiebler** [comment]
Glad you found the problem! Definitely recommend trying typescript if you haven't already, it would've caught this at build time 🙂
