### ISSUE TITLE
Api key is invalid

### ISSUE THREAD

**Issue by UnrealSamu** [tiagosiebler/bybit-api#285]
I m pretty sure that my api key is valid but I got this error
![image](https://github.com/tiagosiebler/bybit-api/assets/65288442/e0e89ab9-39ee-498f-81ac-63362312f908)

**Comment by tiagosiebler** [comment]
99.9% of the time, it is a simple mistake around the API key you're trying to use. Best bet is to create a new API key and make absolutely sure there are no mistakes in what you're providing to the SDK.

**Comment by tiagosiebler** [comment]
Closing this, feel free to reopen if you continue having problems.
