### ISSUE TITLE
order not exists or too late to replace

### ISSUE THREAD

**Issue by shooter01** [tiagosiebler/bybit-api#289]
Hello. Firstly, Thank you for your library, it's awesome!

But, I have an Error
![image](https://github.com/tiagosiebler/bybit-api/assets/47353294/c5265d68-71f8-4056-88ed-b73fcfc0f9de)

My code is:

![Screenshot from 2023-09-17 20-11-15](https://github.com/tiagosiebler/bybit-api/assets/47353294/2956e7a3-82d8-47b7-9837-a8d1d85282ff)

![image](https://github.com/tiagosiebler/bybit-api/assets/47353294/1c090219-39fb-4a43-9ce8-e51d396b0b81)

orderId and orderLinkId is 100% correct, I got them after submitOrder, can you help ?

**Comment by tiagosiebler** [comment]
This is specific to how bybit's API or order system works. Might be related to your parameters and afaik you should send **either** orderId **or** orderLinkId, not both. If you're still having problems, you'll find better suggestions for anything workflow-related in Bybit's support group on telegram: https://t.me/BybitAPI
