### ISSUE TITLE
invalid url in readme to v5 upgrade

### ISSUE THREAD

**Issue by jcardonne** [tiagosiebler/bybit-api#303]
this url is invalid about the v5api upgrade:
`https://bybit-exchange.github.io/docs/v5/upgrade-guide`

**Comment by tiagosiebler** [comment]
Thanks for pointing it out, looks like it moved to here: https://bybit-exchange.github.io/docs/v5/intro#v5-and-v3-interface-mapping-list

Doing some minor readme cleaning here: #304
