### ISSUE TITLE
Cannot Create UTA Account for Sub-user

### ISSUE THREAD

**Issue by arjunChouksey** [tiagosiebler/bybit-api#307]
I wanted to create UTA Account for Subuser, but cannot create since method *createSubMember* does not takes argument *isUta*. 
If this value is not passed Classic Account is created as shown in docs

![image](https://github.com/tiagosiebler/bybit-api/assets/35872809/28ce36c5-ab27-4cc9-aa57-1384507c1989)
 
![image](https://github.com/tiagosiebler/bybit-api/assets/35872809/7119286e-15d3-4119-8124-3ab1f2e9060c)

Is there a way to create Uta account programtically.

**Comment by tiagosiebler** [comment]
Looks like new properties I need to add to `CreateSubMemberParamsV5` - I'll include it in the PR for the next release #306

**Comment by tiagosiebler** [comment]
Fixed in v3.8.0. Let me know if there's anything else missing - thanks!

**Comment by arjunChouksey** [comment]
thanks :)
