### ISSUE TITLE
Get Position Info for multiple pairs

### ISSUE THREAD

**Issue by ne0c0de** [tiagosiebler/bybit-api#308]
Hi,

Current Get Position Info endpoint is giving only one symbol position info even if we pass ```symbol``` as null and ```settleCoin``` as USDT because in this case it's filtering the parameters if there's an open position or not.

So, if I'll give symbol parameter it will return result even if there's no open position for that pair, if I will pass symbol as null and settleCoin as USDT it will return the pairs only if I have an open position on them.

I would like to get all pairs with a single request even if there's no open position for thaat. Is this possible or should I get each pair with a single request (which will hit my request limits)

**Comment by tiagosiebler** [comment]
Hi,

Ah I initially misunderstood your question. Correct me if I still misunderstood - it sounds like you're looking to get all symbols, you don't really need to know if they have an open position or not. Well, if you need open positions too, you could continue doing this to fetch all open positions, but to fetch all pairs you could make a second request to get all symbols. Get tickers might be a good option for that:
https://bybit-exchange.github.io/docs/v5/market/tickers

**Comment by ne0c0de** [comment]
Hi,

My main approach is to get leverage and tradeMode information for all pairs on my system initialization, for this reason I'm currently calling same endpoint for each pairs one by one which is not user friendly. I want to make a single request to get all pairs if it's possible (tickers endpoint is not include this information that I need(

**Comment by tiagosiebler** [comment]
I see what you mean and know the exact functionality on binance but don't see the way on bybit. Let me ask bybit from my side and get back to you.

**Comment by ne0c0de** [comment]
thank you so much

**Comment by tiagosiebler** [comment]
@ne0c0de "Yes. You need to call multiple times. We are trying to support passing multiple symbols ( separated by comma ) for linear"

Not possible right now, you will just need to call it once per symbol...they're working to improve this in future. If you (or anyone else) needs this, I really recommend also talking to bybit (support on the website or the api group on telegram) and letting them know this is important to you. The more people ask, the more likely it gets done!

**Comment by ne0c0de** [comment]
thank you @tiagosiebler so much, is there any official telegram group for bybit api team?

**Comment by tiagosiebler** [comment]
Yes, most of the major exchanges have one. Great place for these kind of questions. This is the one for bybit:
https://t.me/BybitAPI

I also have my own group for dev traders like us using node in the space of algo trading:
https://t.me/nodetraders
