### ISSUE TITLE
Method for setting collateral coin

### ISSUE THREAD

**Issue by arjunChouksey** [tiagosiebler/bybit-api#310]
I want to set Collateral coin for my account as show in docs https://bybit-exchange.github.io/docs/v5/account/set-collateral. But it seems there is no method to to do so. 
Can anybody provide a solution for same. 
Thanks

**Comment by tiagosiebler** [comment]
@arjunChouksey just added via #311 - will be available shortly on npm with version 3.8.2 onwards. thanks
