### ISSUE TITLE
Doubt about Withdraw status

### ISSUE THREAD

**Issue by arjunChouksey** [tiagosiebler/bybit-api#320]
Hey @tiagosiebler , I need help regarding withdraw status to understand about `Reject`, `Fail`,  `MoreInformationRequired` and `Unknown`. More particulary in case what happens to my assets if these status are seen in withdraw records.
 Does assets stay on my account or  will they be refunded after few hours or will not refunded until i raise issue. 

Thanks

**Comment by ajayvignesh01** [comment]
I think you might be better served asking this in the bybit api telegram: https://t.me/BybitAPI

**Comment by tiagosiebler** [comment]
Agree with @ajayvignesh01 - for API-behaviour, best place to ask is in the exchange's very active API group. If you can't get any traction there though, do let me know, but definitely start there.
