### ISSUE TITLE
Demo Trading on Testnet

### ISSUE THREAD

**Issue by Knaackee** [tiagosiebler/bybit-api#337]
At first, thanks for your work! 

I would like to use it with demo trading on the `testnet`, but I am unable to connect. The problem is with the API key.

I have successfully created a key for the `testnet`, but it doesn’t work for `testnet`combined with `demoTrading`.

How can I create an API key for `testnet`+ `demoTrading`?

```
error {
   code: 401,
   message: 'API key is invalid.',
}
```

**Comment by tiagosiebler** [comment]
Might seem a silly question, but what's preventing you from using demo trading with the production environment instead of testnet? The purpose of demo trading is to simulate trading with data on real markets. Testnet is technically already demo/fake trading but with unrealistic markets.

**Comment by Knaackee** [comment]
Not silly at all. The problem is that the account on the testnet has a zero balance.

**Comment by tiagosiebler** [comment]
Perhaps I misunderstood your goal, but what I am suggesting here is to use demo trading in the live environment, not testnet. You can already use testnet without risking any real money, without enabling demo trading.

**Comment by Knaackee** [comment]
Nice idea! Works great. Thanks!
