### ISSUE TITLE
Is there a V5 method: Get Long Short Ratio ?

### ISSUE THREAD

**Issue by Simon1093** [tiagosiebler/bybit-api#339]
Hi! Is there a V5 method: Get Long Short Ratio ? Couldn't find it. Found only in V3 LinearClient -> getLongShortRatio(...)

V5 Method: https://bybit-exchange.github.io/docs/v5/market/long-short-ratio

**Comment by will2022** [comment]
It appears that the feature has not been implemented yet. As a temporary workaround, you might consider sending a GET request to the API URL

**Comment by tiagosiebler** [comment]
Looks like it's missing. PR would be very welcome! Otherwise I'll do my best to add it in the next batch of changes. If anything else is missing please let us know.

**Comment by tiagosiebler** [comment]
Will be added in v3.10.3 via #343 

If any other endpoints are missing or outdated, please feel free to log more issues. Thanks!
