### ISSUE TITLE
Demo Trading Api Key Error

### ISSUE THREAD

**Issue by welteles** [tiagosiebler/bybit-api#341]
I recently generated an API key and secret for my Demo Trading account. However, upon attempting to use them, I encountered the following error message:

![image](https://github.com/tiagosiebler/bybit-api/assets/10013029/c9da067a-4982-4565-9e03-a47ced0c4339)

I'm currently using the latest version of the software. Could you please assist me in resolving this issue?

My Code.

`
import { RestClientV5 } from 'bybit-api';
const client = new RestClientV5({testnet: false, key, secret});
`

**Comment by tiagosiebler** [comment]
You need to include `demoTrading: true` else the SDK doesn't know to use the dedicated demo trading API (different URL from the live environment):
https://github.com/tiagosiebler/bybit-api/blob/master/examples/demo-trading.ts#L19-L37

**Comment by welteles** [comment]
Thank you so Much!
