### ISSUE TITLE
Adding missing endpoints and functionalities 

### ISSUE THREAD

**Issue by JJ-Cro** [tiagosiebler/bybit-api#349]
New features that needs to be done: 

- WEBSOCKET API
https://bybit-exchange.github.io/docs/v5/websocket/trade/guideline

Some missing endpoints: 

1) Position group

POST /v5/position/move-positions
GET /v5/position/move-history
POST /v5/position/confirm-pending-mmr

2) Account group

GET /v5/account/query-dcp-info
And most endpoints below it

Asset group

v5/asset/withdraw/vasp/list

3) User group

GET /v5/user/aff-customer-info

4) Spot margin UTA

GET /v5/spot-margin-trade/data
GET /v5/spot-margin-trade/state

5) Institutional 

POST /v5/ins-loan/association-uid

6) Broker 

All 3 endpoints missing

**Comment by tiagosiebler** [comment]
Only the WS API is missing now, right? @JJ-Cro

**Comment by JJ-Cro** [comment]
Yes

**Comment by JJ-Cro** [comment]
Done!
