### ISSUE TITLE
React App with WebSocket

### ISSUE THREAD

**Issue by Mastero4ek** [tiagosiebler/bybit-api#358]
Hi all. I have a react application (create react app), and a server part of the application in node.js.
How to properly establish a WebSocket connection on the server side and send data to the frontend? 
Or do you need to organize a WebSocket connection on the client side of the application?

I would be grateful for code examples!

**Comment by tiagosiebler** [comment]
For anyone with similar questions, some discussions in the telegram community around here. Lots of ways of doing this and it depends on your exact needs:
https://t.me/nodetraders/32755

Comments from others are welcome/encouraged!
