### ISSUE TITLE
(kline.1.BTCUSDT) failed to subscribe.

### ISSUE THREAD

**Issue by leeian1011** [tiagosiebler/bybit-api#365]
Bug:
![image](https://github.com/user-attachments/assets/f9d0ba4f-555d-45d5-96fd-76c31221e147)

Explanation:
I am currently experiencing a problem with running the WSClient whereby it fails to run `subscribeV5()`.

Notes:
1. I have multiple WSClient scripts that I run simultaneously through worker threads, my server is unable to run the WSClient scripts but is able to connect to wss://stream.bybit.com via wscat.

2. Interestingly, if I write a simple example such as 
```
import { WebsocketClient } from "bybit-api";
import { bybitTopicToHouseTopic } from "../helpers/bybit";

const wsClient = new WebsocketClient({ market: 'v5' });
wsClient.on('update', (data) => {
  try {
    if ('topic' in data) {
      console.info(`${data}`)
    }
  } catch (e) {
    console.warn(`Failed to publish data to topic due to ${e}`);
  }
});

wsClient.subscribeV5("kline.1.BTCUSDT", "linear");
```
and run it on the worker thread pool, this works perfectly fine but my other scripts that had not been change for over 6months + no longer works.

3. I can run this just fine on my local machine, but not on the cloud instance

**Comment by leeian1011** [comment]
After thorough debugging, it all came down to user error. My scripts accepts a symbol input (typically XXXUSDT such as BTCUSDT), however, I just only noticed that the symbol input I've been testing with has been XXX***UDST***.
No problems with your code, and appreciate it a lot!

**Comment by tiagosiebler** [comment]
Glad you found the cause! Thanks for the update
