### ISSUE TITLE
marketUnit not working

### ISSUE THREAD

**Issue by ghost** [tiagosiebler/bybit-api#374]
I tried setting up the market unit to quoteCoin but no matter what you change the order is always placed as baseCoin.

**Comment by tiagosiebler** [comment]
For usage questions on the API itself (e.g. how to use certain parameters to get the behaviour you're looking for), I highly recommend their API group on telegram. There's a link here in their FAQ:
https://www.bybit.com/future-activity/en/developer

Make sure to include an example of how you're trying to use this parameter, so there's no misunderstanding.

**Comment by tiagosiebler** [comment]
Closing this for now. If you found the answer, would be great if you could share it for others with the same question in future. Thanks!
