### ISSUE TITLE
Error from cloudfront when deployed to render

### ISSUE THREAD

**Issue by ShiroyashaDev** [tiagosiebler/bybit-api#380]
Hi, I implemented your Nodejs SDK and deployed it on render.com but I keep on getting error 403.

<img width="562" alt="image" src="https://github.com/user-attachments/assets/8a86a8e4-58ad-40f2-ad25-66d522d939b1">

**Comment by tiagosiebler** [comment]
Can you check where your production environment is located? Bybit (and many other exchanges) block any traffic coming from US IPs.

**Comment by ShiroyashaDev** [comment]
thank you! its working now.
