### ISSUE TITLE
api ZECUSDT SPOT market kline return the same duplicate prices

### ISSUE THREAD

**Issue by git298464** [tiagosiebler/bybit-api#383]
https://api.bybit.com//v5/market/kline?category=spot&symbol=ZECUSDT&interval=60&start=1728904608272&end=1729509408272&limit=20
```
{
  "retCode": 0,
  "retMsg": "OK",
  "result": {
    "category": "spot",
    "symbol": "ZECUSDT",
    "list": [
      [
        "1729508400000",
        "0.81",
        "0.81",
        "0.81",
        "0.81",
        "0",
        "0"
      ],
      // ...
      [
        "1729504800000",
        "0.81",
        "0.81",
        "0.81",
        "0.81",
        "0",
        "0"
      ],
    ]
  },
  "retExtInfo": {
    
  },
  "time": 1729509563594
}
```

**Comment by tiagosiebler** [comment]
For data questions like this where the SDK itself is working as expected, I would recommend reaching out to bybit directly. At a glance it looks like those two candles have 0 volume, so it may be as expected, but if you want confirmation reach out to bybit with this.
