### ISSUE TITLE
Type mismatch on Create Sub UID API Key

### ISSUE THREAD

**Issue by phyzixmusic** [tiagosiebler/bybit-api#385]
bybit-api library asking for an array for strings yet the docs ask for a single string seperated by commas 

![CleanShot 2024-10-25 at 09 52 15](https://github.com/user-attachments/assets/f9cfff32-fd58-4b6a-8cdb-8fe4ba40c1ad)

![CleanShot 2024-10-25 at 09 53 35](https://github.com/user-attachments/assets/9792995a-6fb3-4a3f-b7fd-54bfdcc569ec)

**Comment by JJ-Cro** [comment]
Thanks for pointing it out @phyzixmusic , it will be updated within an hour!

**Comment by JJ-Cro** [comment]
https://github.com/tiagosiebler/bybit-api/pull/386 

PR is active, should be merged shortly by Tiago. Thanks for pointing it out, typos can happen :)

**Comment by tiagosiebler** [comment]
Fixed in #386 - will be on npm shortly. Thanks for reporting this, and thanks @JJ-Cro for the quick fix. Let us know if you catch anything else.
