### ISSUE TITLE
`getTicker` method returns random data

### ISSUE THREAD

**Issue by mavdrix** [tiagosiebler/bybit-api#389]
`getTicker` method returns random data instead of actual values.
https://api.bybit.com/v5/market/tickers?category=spot
In the original request, we have valid prices
![Screenshot 2024-10-29 at 18 28 28](https://github.com/user-attachments/assets/58b97b9a-512e-41d1-9a43-fafa04eb85b5)
![Screenshot 2024-10-29 at 18 29 11](https://github.com/user-attachments/assets/6812225a-7241-4c74-bab5-7ce27c9a46b9)

**Comment by tiagosiebler** [comment]
Can you reproduce the issue? The SDK does not do anything with the data returned by the API, so it's very likely this is just the data that the API returned.

**Comment by mavdrix** [comment]
@tiagosiebler The second screenshot is the data returned by the API and the first one is the data returned from the SDK

**Comment by tiagosiebler** [comment]
I understood that, but do you still see the issue when making the API call with the SDK?

**Comment by tiagosiebler** [comment]
Closing this. If it persists and you can reproduce it, feel free to provide more info. Thanks.
