### ISSUE TITLE
unknown invalid error when submitting market order: 10001, retMsg: ' [a23546bb-6aa4-411f-82ad-709be7c2d914]buy: [55998000,47634000] invalid',

### ISSUE THREAD

**Issue by ne0c0de** [tiagosiebler/bybit-api#390]
Hi,

I'm using bybit api with the current library and creating orders without any errors usually. But Today I tried to create order with these parameters: 

```
  {
    category: 'linear',
    symbol: 'PONKEUSDT',
    side: 'Buy',
    orderType: 'Market',
    qty: '11068',
    orderLinkId: 'CTB_1730716224987_T2_ENTRY'
  }
```

Which is a usual parameters that I'm creating order but I got this error:

```
  {
    rateLimitApi: undefined,
    retCode: 10001,
    retMsg: ' [a23546bb-6aa4-411f-82ad-709be7c2d914]buy: [55998000,47634000] invalid',
    result: {},
    retExtInfo: {},
    time: 1730716225302
  }
  ```

Is anyone that got this kind of error and know the solution?

**Comment by tiagosiebler** [comment]
Strange, are you still seeing this issue or did it just happen once? I'll ask Bybit as well.

**Comment by ne0c0de** [comment]
First time that I got this error and there's no docs about the error code

**Comment by tiagosiebler** [comment]
Is it still happening?

**Comment by ne0c0de** [comment]
Order execution timestamp: [10:30:25.249] (Today)
Error response timestamp: [10:30:25.339]

No, this is onetime error that I got, API working as usual now.

**Comment by tiagosiebler** [comment]
Feedback from bybit:

> This happens when huge volatility results in an order unable to be filled at that price. 
> Market orders are technically (in the backend) just limit orders submitted at a worse price in the internal system to reduce the chance of a flash crash or something similar, ie a trader might submit a market order but they didn't expect it to execute at a price significantly worse than the last price as they know it. 
> In this case the price assigned to the order couldn't be filled as the market moved too quickly.

I've suggested a introducing more specific error code for this in future so it's more obvious and easier to handle, but at least this answers what happened here!

**Comment by ne0c0de** [comment]
Yes, I suspected from the high volatility as well but looking for a workaround to avoid from this kind of errirs but I guess there's no workaround for it..

**Comment by ne0c0de** [comment]
![image](https://github.com/user-attachments/assets/8f5e02a1-328a-4bce-8fea-4368526038c1)

This is the orders that executed on that timestamp

**Comment by tiagosiebler** [comment]
Doesn't seem like it since the issue happens server-side for market orders submitted during volatility...simplest you can do is handle it and if circumstances are still right, resubmit... or perhaps you could use a more specific limit order at the "worst" price you're willing to accept and it should automatically fill as a market order if conditions fit your request

**Comment by tiagosiebler** [comment]
If you use timeInForce set to FOK (FillOrKill) with the limit order suggestion, it would also stop you from having any unfilled orders sitting around, in case the price moves more than expected.

**Comment by ne0c0de** [comment]
> Doesn't seem like it since the issue happens server-side for market orders submitted during volatility...simplest you can do is handle it and if circumstances are still right, resubmit... or perhaps you could use a more specific limit order at the "worst" price you're willing to accept and it should automatically fill as a market order if conditions fit your request

Do you know how much percentage does Bybit allow to execute from last price?

For instance Binance is allowing %5 more (or less for short orders) price from the current market price

**Comment by tiagosiebler** [comment]
Asked:

![telegram-cloud-photo-size-4-5854979704187110066-y](https://github.com/user-attachments/assets/ba315c9c-7a63-4686-8ae8-665fc8fa7c84)

https://www.bybit.com/en/announcement-info/transact-parameters/

Same as Binance it seems.

**Comment by ne0c0de** [comment]
Thank you so much clarification (and shame on my lazyness :D)

**Comment by tiagosiebler** [comment]
I also learnt something today, so this is a win
