### ISSUE TITLE
[BUG] Missing `closedPnl` mapping in `WSAccountOrderV5 `

### ISSUE THREAD

**Issue by soranoo** [tiagosiebler/bybit-api#391]
https://github.com/tiagosiebler/bybit-api/blob/26754f9d8ea59df7eea8e232cda5f2f919d30b99/src/types/websocket.events.ts#L108-L155
(Source Code)

![image](https://github.com/user-attachments/assets/4986c2de-e43c-4b0d-a4ef-99391084a092)
 (Pic.1)

![image](https://github.com/user-attachments/assets/313d5c50-d001-417f-91b1-457779ee38e6)

 (Pic.2)

According to the returned json (Pic.1) the `closedPnl` is included while it isn't reflected in the type  (Pic.2).

**Comment by JJ-Cro** [comment]
Can you make a PR for it? So @tiagosiebler can merge it quickly!

**Comment by soranoo** [comment]
Sure!
